CREATE TABLE elem_voc 
(
    Orders int,
    Vocabulary nvarchar(300) primary key,
    Chinese	nvarchar(300)
);

INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('1', N'a', N'[冠詞] 一個');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('2', N'about', N'[介系詞] 1. 大約；2. 關於...');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('3', N'actor', N'[名詞] 男演員');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('4', N'actress', N'[名詞] 女演員');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('5', N'after', N'[介系詞] 在...之後');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('6', N'afternoon', N'[名詞] 下午');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('7', N'again', N'[副詞] 再一次、又一次');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('8', N'airplane', N'[名詞] 飛機 (= plane)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('9', N'airport', N'[名詞] 機場');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('10', N'all', N'[限定詞] 全部的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('11', N'always', N'[副詞] 總是、永遠');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('12', N'an', N'[冠詞] 一個');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('13', N'and', N'[連接詞] 和');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('14', N'angry', N'[形容詞] 生氣的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('15', N'animal', N'[名詞] 動物');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('16', N'answer', N'[動詞] 回答');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('17', N'apple', N'[名詞] 蘋果');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('18', N'April', N'[名詞] 四月');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('19', N'arm', N'[名詞] 手臂');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('20', N'art', N'[名詞] 美術、藝術');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('21', N'ask', N'[動詞] 問');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('22', N'at', N'[介系詞] 在(某處)、在(時刻)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('23', N'August', N'[名詞] 八月');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('24', N'aunt', N'[名詞] 阿姨、姑姑、伯母、舅媽');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('25', N'away', N'[副詞] 離開');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('26', N'baby', N'[名詞] 嬰兒');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('27', N'back', N'[名詞] 背;[副詞] 向後、回原處');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('28', N'bad', N'[形容詞] 不好的、壞的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('29', N'bag', N'[名詞] 袋子');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('30', N'ball', N'[名詞] 球');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('31', N'banana', N'[名詞] 香蕉');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('32', N'bank', N'[名詞] 銀行');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('33', N'baseball', N'[名詞] 棒球');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('34', N'basketball', N'[名詞] 籃球');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('35', N'bathroom', N'[名詞] 浴室');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('36', N'be', N'[助動詞] 是 (is, am, are)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('37', N'beach', N'[名詞] 海灘');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('38', N'bear', N'[名詞] 熊');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('39', N'beautiful', N'[形容詞] 美麗的、漂亮的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('40', N'because', N'[連接詞] 因為');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('41', N'bed', N'[名詞] 床');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('42', N'bedroom', N'[名詞] 臥房');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('43', N'bee', N'[名詞] 蜜蜂');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('44', N'beef', N'[名詞] 牛肉');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('45', N'before', N'[介系詞, 連接詞] 在...之前');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('46', N'behind', N'[介系詞] 在...後面');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('47', N'bicycle', N'[名詞] 腳踏車 (= bike)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('48', N'big', N'[形容詞] 大的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('49', N'bike', N'[名詞] 腳踏車 (= bicycle)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('50', N'bird', N'[名詞] 鳥');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('51', N'birthday', N'[名詞] 生日');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('52', N'bite', N'[動詞] 咬');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('53', N'black', N'[形容詞] 黑色的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('54', N'blackboard', N'[名詞] 黑板');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('55', N'blue', N'[形容詞] 藍色的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('56', N'boat', N'[名詞] 船');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('57', N'book', N'[名詞] 書、書本');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('58', N'bookstore', N'[名詞] 書店');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('59', N'bored', N'[形容詞] 覺得無聊的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('60', N'boring', N'[形容詞] 令人無聊的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('61', N'both', N'[限定詞] 兩個都');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('62', N'bottle', N'[名詞] 瓶子');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('63', N'box', N'[名詞] 箱子');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('64', N'boy', N'[名詞] 男孩');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('65', N'bread', N'[名詞] 麵包');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('66', N'breakfast', N'[名詞] 早餐');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('67', N'brother', N'[名詞] 哥哥、弟弟');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('68', N'brown', N'[形容詞] 咖啡色的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('69', N'brush', N'[動詞] 用刷子刷');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('70', N'bus', N'[名詞] 公車');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('71', N'bus stop', N'[名詞] 公車站');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('72', N'busy', N'[形容詞] 忙碌的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('73', N'but', N'[連接詞] 但是');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('74', N'butterfly', N'[名詞] 蝴蝶');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('75', N'buy', N'[動詞] 買');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('76', N'by', N'[介系詞] 在...旁邊');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('77', N'bye', N'[感嘆詞] 再見 (= goodbye)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('78', N'cake', N'[名詞] 蛋糕');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('79', N'call', N'[動詞] 打電話給...');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('80', N'can', N'[助動詞]、[名詞] 可以;罐子');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('81', N'candy', N'[名詞] 糖果');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('82', N'cap', N'[名詞] 棒球帽');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('83', N'car', N'[名詞] 車子');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('84', N'card', N'[名詞] 卡片');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('85', N'cat', N'[名詞] 貓');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('86', N'cellphone', N'[名詞] 手機');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('87', N'chair', N'[名詞] 椅子');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('88', N'chicken', N'[名詞] 雞;雞肉');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('89', N'Chinese', N'[名詞] 中文');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('90', N'chocolate', N'[名詞] 巧克力');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('91', N'chopsticks', N'[名詞] 筷子');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('92', N'class', N'[名詞] 課；班級');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('93', N'classroom', N'[名詞] 教室');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('94', N'clean', N'[形容詞] 乾淨的;[動詞] 清理');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('95', N'climb', N'[動詞] 爬、攀爬');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('96', N'clock', N'[名詞] 時鐘');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('97', N'close', N'[動詞] 關');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('98', N'clothes', N'[名詞] 衣服');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('99', N'cloudy', N'[形容詞] 多雲的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('100', N'coat', N'[名詞] 外套');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('101', N'coffee', N'[名詞] 咖啡');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('102', N'coke', N'[名詞] 可樂');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('103', N'cold', N'[形容詞] 寒冷的;[名詞] 感冒');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('104', N'color', N'[名詞] 顏色');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('105', N'come', N'[動詞] 來');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('106', N'computer', N'[名詞] 電腦');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('107', N'cook', N'[名詞] 廚師;[動詞] 做飯');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('108', N'cookies', N'[名詞] 餅乾');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('109', N'cool', N'[形容詞] 涼爽的、清涼的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('110', N'cousin', N'[名詞] 堂兄（弟、姊、妹）');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('111', N'cow', N'[名詞] 乳牛');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('112', N'cry', N'[動詞] 哭、哭泣');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('113', N'cup', N'[名詞] 杯子');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('114', N'cute', N'[形容詞] 可愛的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('115', N'dad', N'[名詞] 爸爸 (= father; daddy)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('116', N'daddy', N'[名詞] 爸爸 (= father; dad)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('117', N'dance', N'[動詞] 跳舞');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('118', N'daughter', N'[名詞] 女兒');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('119', N'day', N'[名詞] 天');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('120', N'December', N'[名詞] 十二月');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('121', N'department store', N'[名詞] 百貨公司');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('122', N'desk', N'[名詞] 桌子');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('123', N'different', N'[形容詞] 不一樣的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('124', N'dining room', N'[名詞] (家裡的)餐廳');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('125', N'dinner', N'[名詞] 晚餐');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('126', N'dirty', N'[形容詞] 髒的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('127', N'dish', N'[名詞] 碟子、盤子');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('128', N'do', N'[助動詞] 助動詞;[動詞] 做');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('129', N'doctor', N'[名詞] 醫生');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('130', N'dog', N'[名詞] 狗');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('131', N'doll', N'[名詞] 玩偶');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('132', N'dollar', N'[名詞] 元');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('133', N'door', N'[名詞] 門');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('134', N'draw', N'[動詞] 畫、描畫');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('135', N'dream', N'[名詞] 夢');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('136', N'dress', N'[名詞] 洋裝');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('137', N'drink', N'[動詞] 喝');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('138', N'drive', N'[動詞] 開車');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('139', N'driver', N'[名詞] 司機、駕駛員');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('140', N'drum', N'[名詞] 鼓');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('141', N'duck', N'[名詞] 鴨子;鴨肉');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('142', N'dumpling', N'[名詞] 水餃');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('143', N'ear', N'[名詞] 耳朵');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('144', N'early', N'[形容詞] 早到的;[副詞] 早到地');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('145', N'easy', N'[形容詞] 簡單的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('146', N'eat', N'[動詞] 吃');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('147', N'egg', N'[名詞] 蛋');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('148', N'eight', N'[數字] 八');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('149', N'eighteen', N'[數字] 十八');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('150', N'eighty', N'[數字] 八十');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('151', N'elephant', N'[名詞] 大象');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('152', N'eleven', N'[數字] 十一');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('153', N'email', N'[名詞] 電子郵件');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('154', N'English', N'[名詞] 英文');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('155', N'enjoy', N'[動詞] 享受、喜歡');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('156', N'eraser', N'[名詞] 橡皮擦');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('157', N'evening', N'[名詞] 傍晚');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('158', N'every', N'[限定詞] 每一個');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('159', N'excited', N'[形容詞] 覺得興奮的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('160', N'exciting', N'[形容詞] 令人興奮的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('161', N'excuse me', N'[感嘆詞] 不好意思、對不起');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('162', N'eye', N'[名詞] 眼睛');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('163', N'face', N'[名詞] 臉');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('164', N'fall', N'[名詞]、[動詞] 秋天;掉落');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('165', N'family', N'[名詞] 家庭、家人');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('166', N'fan', N'[名詞] 電扇');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('167', N'farmer', N'[名詞] 農夫');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('168', N'fast', N'[形容詞] 快速的; [副詞] 快速地');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('169', N'father', N'[名詞] 爸爸 (= dad; daddy)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('170', N'favorite', N'[形容詞] 最喜歡的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('171', N'February', N'[名詞] 二月');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('172', N'feel', N'[動詞] 感受、感覺');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('173', N'feet', N'[名詞] 腳 (複數)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('174', N'fifteen', N'[數字] 十五');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('175', N'fifty', N'[數字] 五十');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('176', N'find', N'[動詞] 找');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('177', N'fine', N'[形容詞] 很好的、很不錯的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('178', N'fire station', N'[名詞] 消防站');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('179', N'first', N'[數字] 第一');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('180', N'fish', N'[名詞] 魚、魚肉; [動詞] 釣魚');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('181', N'five', N'[數字] 五');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('182', N'floor', N'[名詞] 地板');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('183', N'flower', N'[名詞] 花');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('184', N'fly', N'[動詞] 飛、飛行');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('185', N'food', N'[名詞] 食物');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('186', N'foot', N'[名詞] 腳');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('187', N'football', N'[名詞] 足球 (UK; 英式英語)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('188', N'for', N'[介系詞] 給、為了(某人、物)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('189', N'fork', N'[名詞] 叉子');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('190', N'forty', N'[數字] 四十');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('191', N'four', N'[數字] 四');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('192', N'fourteen', N'[數字] 十四');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('193', N'free', N'[形容詞] 免費的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('194', N'French fries', N'[名詞] 薯條');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('195', N'Friday', N'[名詞] 星期五');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('196', N'fridge', N'[名詞] 電冰箱 (= refrigerator)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('197', N'friend', N'[名詞] 朋友');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('198', N'frog', N'[名詞] 青蛙');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('199', N'from', N'[介系詞] 從(某處)/(某時刻)/(某人)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('200', N'fruit', N'[名詞] 水果');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('201', N'full', N'[形容詞] 飽的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('202', N'fun', N'[形容詞] 有趣的;[名詞] 樂趣');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('203', N'game', N'[名詞] 遊戲、比賽');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('204', N'garden', N'[名詞] 院子、花園');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('205', N'get', N'[動詞] 得到、收到');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('206', N'gift', N'[名詞] 禮物');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('207', N'girl', N'[名詞] 女孩');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('208', N'give', N'[動詞] 給');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('209', N'glass', N'[名詞] 玻璃杯');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('210', N'glasses', N'[名詞] 眼鏡');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('211', N'glue', N'[名詞] 膠水');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('212', N'go', N'[動詞] 去、走');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('213', N'good', N'[形容詞] 好的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('214', N'goodbye', N'[感嘆詞] 再見 (= bye)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('215', N'grandfather', N'[名詞] 外公、爺爺 (= grandpa)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('216', N'grandma', N'[名詞] 外婆、奶奶 (= grandmother)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('217', N'grandmother', N'[名詞] 外婆、奶奶 (= grandma)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('218', N'grandpa', N'[名詞] 外公、爺爺 (= grandfather)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('219', N'grape', N'[名詞] 葡萄');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('220', N'gray', N'[形容詞] 灰色的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('221', N'great', N'[形容詞] 很棒的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('222', N'green', N'[形容詞] 綠色的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('223', N'grow', N'[動詞] 成長、長大');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('224', N'hair', N'[名詞] 頭髮');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('225', N'hamburger', N'[名詞] 漢堡');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('226', N'hand', N'[名詞] 手');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('227', N'happy', N'[形容詞] 開心的、高興的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('228', N'hard', N'[形容詞] 困難的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('229', N'hat', N'[名詞] 帽子');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('230', N'have', N'[助動詞] 助動詞;[動詞] 有');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('231', N'he', N'[代名詞] 他');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('232', N'head', N'[名詞] 頭');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('233', N'headache', N'[名詞] 頭痛');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('234', N'heavy', N'[形容詞] 重的 (人)、重的 (物品)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('235', N'hello', N'[感嘆詞] 哈囉');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('236', N'help', N'[動詞] 幫助');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('237', N'her', N'[限定詞] 她的;[代名詞] 她');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('238', N'here', N'[副詞] 這裡');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('239', N'hi', N'[感嘆詞] 嗨');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('240', N'high', N'[形容詞] 高的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('241', N'hike', N'[動詞] 健行');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('242', N'him', N'[代名詞] 他(受詞)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('243', N'hippo', N'[名詞] 河馬');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('244', N'his', N'[限定詞] 他的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('245', N'hit', N'[動詞] 打、碰撞');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('246', N'home', N'[名詞] 家庭');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('247', N'homework', N'[名詞] 回家作業');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('248', N'hope', N'[動詞] 希望');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('249', N'horse', N'[名詞] 馬');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('250', N'hospital', N'[名詞] 醫院');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('251', N'hot', N'[形容詞] 熱的、燙的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('252', N'house', N'[名詞] 房子');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('253', N'how', N'[副詞] 如何...');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('254', N'hundred', N'[數字] 一百');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('255', N'hungry', N'[形容詞] 餓的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('256', N'hurry', N'[動詞] 趕快、急忙');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('257', N'hurt', N'[動詞] 受傷');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('258', N'I', N'[代名詞] 我');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('259', N'ice cream', N'[名詞] 冰淇淋');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('260', N'in', N'[介系詞] 在...裡面、在某短時間裡');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('261', N'in front of', N'[介系詞] 在...前面');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('262', N'inside', N'[介系詞] 在...裡面、向...裡面');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('263', N'interesting', N'[形容詞] 有趣的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('264', N'it', N'[代名詞] 它、牠');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('265', N'its', N'[限定詞] 它的、牠的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('266', N'jacket', N'[名詞] 夾克、外套');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('267', N'January', N'[名詞] 一月');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('268', N'job', N'[名詞] 工作、職業');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('269', N'juice', N'[名詞] 果汁');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('270', N'July', N'[名詞] 七月');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('271', N'jump', N'[動詞] 跳');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('272', N'June', N'[名詞] 六月');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('273', N'lake', N'[名詞] 湖');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('274', N'lamp', N'[名詞] 燈');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('275', N'last', N'[限定詞] [形容詞] 最後的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('276', N'late', N'[形容詞] 晚到的;[副詞] 晚到地');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('277', N'laugh', N'[動詞] 笑');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('278', N'lazy', N'[形容詞] 懶惰的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('279', N'left', N'[形容詞] 左邊的;[副詞] 左邊地');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('280', N'leg', N'[名詞] 腿');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('281', N'lemon', N'[名詞] 檸檬');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('282', N'let''s', N'[動詞] 讓我們...');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('283', N'library', N'[名詞] 圖書館');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('284', N'light', N'[形容詞] 輕的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('285', N'like', N'[動詞] 喜歡');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('286', N'lion', N'[名詞] 獅子');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('287', N'listen', N'[動詞] 聽');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('288', N'live', N'[動詞] 住');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('289', N'living room', N'[名詞] 客廳');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('290', N'long', N'[形容詞] 長的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('291', N'look', N'[動詞] 看、看起來');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('292', N'love', N'[動詞] 愛、喜愛');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('293', N'lunch', N'[名詞] 午餐');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('294', N'mad', N'[形容詞] 生氣的、氣憤的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('295', N'mail', N'[名詞] 信');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('296', N'mailman', N'[名詞] 郵差');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('297', N'make', N'[動詞] 做、製造');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('298', N'man', N'[名詞] 男人');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('299', N'many', N'[限定詞] [形容詞] 許多(例如many flowers)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('300', N'March', N'[名詞] 三月');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('301', N'marker', N'[名詞] 麥克筆');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('302', N'market', N'[名詞] 市場');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('303', N'math', N'[名詞] 數學');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('304', N'May', N'[名詞] 五月');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('305', N'maybe', N'[副詞] 也許');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('306', N'me', N'[代名詞] 我(受詞)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('307', N'meal', N'[名詞] 餐');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('308', N'meet', N'[動詞] 遇見、會面');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('309', N'men', N'[名詞] 男人 (複數)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('310', N'mice', N'[名詞] 老鼠 (複數)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('311', N'milk', N'[名詞] 牛奶');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('312', N'miss', N'[動詞] 想念');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('313', N'mom', N'[名詞] 媽媽 (= mother; mommy)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('314', N'mommy', N'[名詞] 媽媽 (= mother; mom)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('315', N'Monday', N'[名詞] 星期一');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('316', N'money', N'[名詞] 錢');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('317', N'monkey', N'[名詞] 猴子');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('318', N'month', N'[名詞] 月');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('319', N'moon', N'[名詞] 月亮');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('320', N'mop', N'[動詞] 用拖把拖地');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('321', N'more', N'[限定詞] [副詞] 更多、較多');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('322', N'morning', N'[名詞] 早上');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('323', N'mother', N'[名詞] 媽媽 (= mom; mommy)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('324', N'motorcycle', N'[名詞] 摩托車');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('325', N'mountain', N'[名詞] 山');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('326', N'mouse', N'[名詞] 老鼠');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('327', N'mouth', N'[名詞] 嘴巴');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('328', N'movie', N'[名詞] 電影');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('329', N'movie theater', N'[名詞] 電影院');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('330', N'Mr.', N' 先生');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('331', N'Mrs.', N' 太太');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('332', N'MRT', N'[名詞] 捷運');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('333', N'much', N'[限定詞] [副詞] 許多(例如much water)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('334', N'museum', N'[名詞] 博物館');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('335', N'music', N'[名詞] 音樂');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('336', N'my', N'[限定詞] 我的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('337', N'name', N'[名詞] 名字');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('338', N'near', N'[介系詞] 靠近、接近');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('339', N'need', N'[動詞] 需要');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('340', N'never', N'[副詞] 不曾');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('341', N'new', N'[形容詞] 新的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('342', N'next to', N'[介系詞] 在...旁邊');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('343', N'nice', N'[形容詞] 令人愉快的、宜人的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('344', N'night', N'[名詞] 晚上');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('345', N'nine', N'[數字] 九');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('346', N'nineteen', N'[數字] 十九');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('347', N'ninety', N'[數字] 九十');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('348', N'no', N'[副詞] 不');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('349', N'noodles', N'[名詞] 麵');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('350', N'nose', N'[名詞] 鼻子');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('351', N'not', N'[副詞] 不、沒有');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('352', N'nothing', N'[代名詞] 什麼都沒有');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('353', N'November', N'[名詞] 十一月');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('354', N'now', N'[副詞] 現在');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('355', N'number', N'[名詞] 數字');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('356', N'nurse', N'[名詞] 護士');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('357', N'o''clock', N'[副詞] ...點鐘');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('358', N'October', N'[名詞] 十月');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('359', N'of', N'[介系詞] ...的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('360', N'off', N'[介系詞] 離開、從...去掉');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('361', N'office', N'[名詞] 辦公室');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('362', N'OK', N'[形容詞] 好的;[副詞] 沒事');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('363', N'old', N'[形容詞] 1. 年紀、年齡；2. 老的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('364', N'on', N'[介系詞] 在...上面；在(某一天)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('365', N'one', N'[數字] 一');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('366', N'only', N'[形容詞]僅有的;[副詞] 唯一地');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('367', N'open', N'[動詞] 開');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('368', N'orange', N'[形容詞] 橘色的;[名詞] 橘子');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('369', N'other', N'[形容詞] [代名詞] [限定詞] 其他的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('370', N'our', N'[限定詞] 我們的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('371', N'out', N'[介系詞] 向外地');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('372', N'outside', N'[介系詞] 在...外面、向...外面');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('373', N'over', N'[介系詞] 在...上方');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('374', N'paint', N'[動詞] 用顏料畫、刷油漆');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('375', N'pair', N'[名詞] 一雙、一對');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('376', N'panda', N'[名詞] 大貓熊');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('377', N'pants', N'[名詞] 長褲');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('378', N'paper', N'[名詞] 紙張');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('379', N'parent', N'[名詞] 父母親');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('380', N'park', N'[名詞] 公園');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('381', N'party', N'[名詞] 派對');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('382', N'PE', N'[名詞] 體育（課）');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('383', N'peach', N'[名詞] 桃子');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('384', N'pen', N'[名詞] 筆、鋼筆');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('385', N'pencil', N'[名詞] 鉛筆');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('386', N'people', N'[名詞] 人 (複數)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('387', N'person', N'[名詞] 人');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('388', N'pet', N'[名詞] 寵物');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('389', N'photo', N'[名詞] 照片');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('390', N'piano', N'[名詞] 鋼琴');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('391', N'pick up', N'[動詞] 撿起、接（人）、接（電話）');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('392', N'picture', N'[名詞] 圖片、照片');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('393', N'pie', N'[名詞] 派');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('394', N'pig', N'[名詞] 豬');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('395', N'pink', N'[形容詞] 粉紅色的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('396', N'pizza', N'[名詞] 披薩');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('397', N'plane', N'[名詞] 飛機 (= airplane)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('398', N'play', N'[動詞] 玩');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('399', N'please', N'[感嘆詞] 請');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('400', N'pocket', N'[名詞] 口袋');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('401', N'police officer', N'[名詞] 警察');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('402', N'police station', N'[名詞] 警察局');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('403', N'pork', N'[名詞] 豬肉');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('404', N'post office', N'[名詞] 郵局');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('405', N'pretty', N'[形容詞] 漂亮的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('406', N'pumpkin', N'[名詞] 南瓜');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('407', N'purple', N'[形容詞] 紫色的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('408', N'put', N'[動詞] 放');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('409', N'question', N'[名詞] 問題');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('410', N'quiet', N'[形容詞] 安靜的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('411', N'rabbit', N'[名詞] 兔子');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('412', N'rain', N'[名詞] 雨水;[動詞] 下雨');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('413', N'rainbow', N'[名詞] 彩虹');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('414', N'rainy', N'[形容詞] 下雨的、多雨的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('415', N'read', N'[動詞] 閱讀');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('416', N'ready', N'[形容詞] 準備好的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('417', N'really', N'[副詞] 真正地');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('418', N'red', N'[形容詞] 紅色的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('419', N'refrigerator', N'[名詞] 電冰箱 (= fridge)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('420', N'restaurant', N'[名詞] 餐廳');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('421', N'restroom', N'[名詞] 洗手間、廁所');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('422', N'rice', N'[名詞] 米飯');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('423', N'ride', N'[動詞] 騎（機車、腳踏車等）');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('424', N'right', N'[形容詞] 對的;[副詞] 右邊地');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('425', N'river', N'[名詞] 河流');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('426', N'robot', N'[名詞] 機器人');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('427', N'ruler', N'[名詞] 尺');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('428', N'run', N'[動詞] 跑、跑步');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('429', N'table', N'[名詞] 桌子');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('430', N'take', N'[動詞] 攜帶、拿取');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('431', N'talk', N'[動詞] 說話、談話');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('432', N'tall', N'[形容詞] 高的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('433', N'taste', N'[動詞] 嚐起來');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('434', N'taxi', N'[名詞] 計程車');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('435', N'tea', N'[名詞] 茶');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('436', N'teacher', N'[名詞] 老師');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('437', N'teeth', N'[名詞] 牙齒 (複數)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('438', N'telephone', N'[名詞] 電話');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('439', N'television', N'[名詞] 電視 (= TV)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('440', N'tell', N'[動詞] 告訴、告知');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('441', N'ten', N'[數字] 十');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('442', N'test', N'[名詞] 考試');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('443', N'than', N'[介系詞] 比');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('444', N'thank', N'[動詞] 感謝（某人）');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('445', N'that', N'[限定詞] 那個');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('446', N'the', N'[冠詞] 這');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('447', N'their', N'[限定詞] 他們的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('448', N'them', N'[代名詞] 他們(受詞)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('449', N'then', N'[副詞] 然後、接著');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('450', N'there', N'[副詞] 那裡');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('451', N'these', N'[限定詞] 這些');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('452', N'they', N'[代名詞] 他們');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('453', N'thin', N'[形容詞] 瘦的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('454', N'thing', N'[名詞] 東西、物');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('455', N'third', N'[數字] 第三');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('456', N'thirsty', N'[形容詞] 口渴的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('457', N'thirteen', N'[數字] 十三');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('458', N'thirty', N'[數字] 三十');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('459', N'this', N'[限定詞] 這個');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('460', N'those', N'[限定詞] 那些');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('461', N'three', N'[數字] 三');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('462', N'Thursday', N'[名詞] 星期四');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('463', N'ticket', N'[名詞] 票');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('464', N'tiger', N'[名詞] 老虎');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('465', N'time', N'[名詞] 時間');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('466', N'tired', N'[形容詞] 疲累的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('467', N'to', N'[介系詞] 向、朝、對著');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('468', N'today', N'[名詞] 今天');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('469', N'together', N'[副詞] 一起');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('470', N'tomorrow', N'[名詞] 明天');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('471', N'too', N'[副詞] 1. 也；2. 太...');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('472', N'tooth', N'[名詞] 牙齒');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('473', N'toothache', N'[名詞] 牙痛');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('474', N'touch', N'[動詞] 觸碰');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('475', N'towel', N'[名詞] 毛巾');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('476', N'toy', N'[名詞] 玩具');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('477', N'train', N'[名詞] 火車');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('478', N'trash', N'[名詞] 垃圾');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('479', N'tree', N'[名詞] 樹');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('480', N'trip', N'[名詞] （短程的）旅行');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('481', N'truck', N'[名詞] 卡車');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('482', N'try', N'[動詞] 嘗試');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('483', N'T-shirt', N'[名詞] T 恤');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('484', N'Tuesday', N'[名詞] 星期二');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('485', N'turn', N'[動詞] 轉彎');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('486', N'turtle', N'[名詞] 烏龜');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('487', N'TV', N'[名詞] 電視 (= television)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('488', N'twelve', N'[數字] 十二');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('489', N'twenty', N'[數字] 二十');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('490', N'two', N'[數字] 二');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('491', N'typhoon', N'[名詞] 颱風');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('492', N'umbrella', N'[名詞] 傘');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('493', N'uncle', N'[名詞] 叔叔、舅舅、姑丈、姨丈');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('494', N'under', N'[介系詞] 在...下方');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('495', N'up', N'[介系詞] 向上');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('496', N'us', N'[代名詞] 我們(受詞)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('497', N'usually', N'[副詞] 通常');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('498', N'vacation', N'[名詞] 假期');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('499', N'very', N'[副詞] 非常');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('500', N'wait', N'[動詞] 等、等待');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('501', N'waiter', N'[名詞] 男服務生');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('502', N'waitress', N'[名詞] 女服務生');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('503', N'wake', N'[動詞] 醒來、喚醒');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('504', N'walk', N'[動詞] 走路');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('505', N'wall', N'[名詞] 牆壁');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('506', N'want', N'[動詞] 想要');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('507', N'warm', N'[形容詞] 溫暖的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('508', N'wash', N'[動詞] 洗');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('509', N'watch', N'[名詞] 手錶:[動詞] 看');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('510', N'water', N'[名詞] 水');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('511', N'watermelon', N'[名詞] 西瓜');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('512', N'way', N'[名詞] 路、方向');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('513', N'we', N'[代名詞] 我們');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('514', N'wear', N'[動詞] 穿、戴');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('515', N'weather', N'[名詞] 天氣');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('516', N'Wednesday', N'[名詞] 星期三');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('517', N'week', N'[名詞] 星期');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('518', N'welcome', N'[動詞] 歡迎');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('519', N'well', N'[形容詞] 好的;[副詞] 健康地');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('520', N'wet', N'[形容詞] 潮濕的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('521', N'whale', N'[名詞] 鯨魚');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('522', N'what', N'[代名詞] 什麼...');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('523', N'when', N'[副詞] 何時...');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('524', N'where', N'[副詞] 在哪裡...');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('525', N'which', N'[限定詞] 哪一個...');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('526', N'white', N'[形容詞] 白色的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('527', N'who', N'[代名詞] 誰...');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('528', N'whose', N'[限定詞] 誰的...');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('529', N'why', N'[副詞] 為什麼...');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('530', N'will', N'[助動詞] 將會');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('531', N'win', N'[動詞] 贏');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('532', N'wind', N'[名詞] 風');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('533', N'window', N'[名詞] 窗戶');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('534', N'windy', N'[形容詞] 風大的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('535', N'winter', N'[名詞] 冬天');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('536', N'with', N'[介系詞] 和...一起');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('537', N'woman', N'[名詞] 女人');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('538', N'women', N'[名詞] 女人 (複數)');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('539', N'wonderful', N'[形容詞] 很棒的、精彩的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('540', N'word', N'[名詞] 字');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('541', N'work', N'[名詞] 工作');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('542', N'worker', N'[名詞] 工作者');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('543', N'worry', N'[動詞] 擔心');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('544', N'write', N'[動詞] 寫');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('545', N'year', N'[名詞] 年');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('546', N'yellow', N'[形容詞] 黃色的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('547', N'yes', N'[副詞] 是');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('548', N'yesterday', N'[名詞] 昨天');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('549', N'you', N'[代名詞] 你、你們');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('550', N'young', N'[形容詞] 年輕的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('551', N'your', N'[限定詞] 你的、你們的');
INSERT INTO elem_voc (Orders, Vocabulary, Chinese) VALUES ('552', N'yummy', N'[形容詞] 好吃的、美味的');
