CREATE TABLE phrase_test 
(
    Orders	int,
    Test nvarchar(300),
    Year varchar(300),
    Phrase nvarchar(300),
    Chinese	nvarchar(300)
);

INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('1', N'指考', N'110', N'wear out', N'磨損 ; 耗盡');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('2', N'指考', N'110', N'break through', N'突破 ; 打破');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('3', N'指考', N'110', N'heat up', N'加熱 ; 使 ... 變暖');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('4', N'指考', N'110', N'in short', N'總⽽⾔之 ; 簡⽽⾔之');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('5', N'指考', N'109', N'serve as', N'充當 ; 起 … 的作⽤');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('6', N'指考', N'109', N'fight for', N'為 ... ⽽戰');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('7', N'指考', N'109', N'persist in', N'堅持');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('8', N'指考', N'109', N'correspond to', N'相當於 ; 符合');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('9', N'指考', N'109', N'toss out', N'丟棄 ; 扔掉');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('10', N'指考', N'109', N'get off', N'離開');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('11', N'指考', N'109', N'catch up', N'趕上');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('12', N'指考', N'109', N'carry on', N'繼續');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('13', N'指考', N'108', N'if any', N'若有的話');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('14', N'指考', N'108', N'among others', N'其中 ; 尤其');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('15', N'指考', N'108', N'in short', N'總⽽⾔之 ; 簡⽽⾔之');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('16', N'指考', N'108', N'at best', N'充其量 ; 頂多');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('17', N'指考', N'108', N'at large', N'逍遙法外 ;普遍地 ; 全體地');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('18', N'指考', N'108', N'in service', N'服勤中');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('19', N'指考', N'108', N'by contrast', N'相比之下');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('20', N'指考', N'108', N'under control', N'在掌控之下');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('21', N'指考', N'107', N'check out', N'檢查');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('22', N'指考', N'107', N'watch over', N'保護 ; 照顧');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('23', N'指考', N'107', N'speak of', N'談到 ; 論及');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('24', N'指考', N'107', N'trade with', N'和 … 貿易');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('25', N'指考', N'107', N'in spite of', N'儘管');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('26', N'指考', N'107', N'as a result of', N'由於');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('27', N'指考', N'107', N'to the best of... (my knowledge/my ability)', N'就我所知 / 就我能⼒所及');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('28', N'指考', N'107', N'for the sake of', N'由於 ; 為了');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('29', N'指考', N'106', N'put up with', N'容忍 ; 忍受');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('30', N'指考', N'106', N'crack down on', N'打擊 ; 鎮壓');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('31', N'指考', N'106', N'give in to', N'屈服 ; 讓步');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('32', N'指考', N'106', N'look out for', N'照顧 ;留⼼ ; 注意尋找');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('33', N'指考', N'106', N'subject to', N'受到 … 的影響');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('34', N'指考', N'106', N'accustomed to', N'習慣於');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('35', N'指考', N'106', N'blessed with', N'在 ... ⽅⾯有福');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('36', N'指考', N'106', N'familiar with', N'熟悉');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('37', N'指考', N'105', N'long before', N'很早以前 ; 很久以前');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('38', N'指考', N'105', N'close to', N'接近於 ; 靠近');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('39', N'指考', N'105', N'aside from', N'besides 除此之外 ( 包含 );except for 除了 … 之外 ( 不包含 )');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('40', N'指考', N'105', N'soon after', N'不久之後');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('41', N'指考', N'105', N'in addition to', N'除 ... 之外');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('42', N'指考', N'105', N'with respect to', N'關於 ; ⾄於');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('43', N'指考', N'104', N'cater to', N'滿⾜或提供需求');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('44', N'指考', N'104', N'depend on', N'取決於');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('45', N'指考', N'104', N'go after sb/sth', N'追趕 ; 追捕 ;謀求 ; 追逐');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('46', N'指考', N'104', N'identify with', N'認同 ( 某⼈ ); 與 ( 某⼈ ) 產⽣共鳴');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('47', N'指考', N'104', N'above all', N'最重要的 ; 尤其');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('48', N'指考', N'104', N'as it appears', N'看起來');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('49', N'指考', N'104', N'to some extent', N'在某種程度上');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('50', N'指考', N'104', N'come across', N'碰到');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('51', N'指考', N'104', N'sweep through', N'席捲');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('52', N'指考', N'103', N'in short', N'簡⾔之 ; 總之');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('53', N'指考', N'102', N'by all means', N'好的 ; 當然');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('54', N'指考', N'102', N'as a result', N'由於');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('55', N'指考', N'102', N'on the other hand', N'另⼀⽅⾯');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('56', N'指考', N'102', N'out of luck', N'運氣不好');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('57', N'指考', N'102', N'in the dark', N'蒙在⿎底 ; ⼀無所知');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('58', N'指考', N'102', N'off the record', N'下說的 ; 不供發表的');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('59', N'指考', N'102', N'on the rise', N'在上升');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('60', N'指考', N'102', N'so that', N'為了 ; 以便');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('61', N'指考', N'102', N'as soon as', N'⼀ ... 就');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('62', N'指考', N'102', N'in case of', N'以防萬⼀');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('63', N'指考', N'102', N'ever since', N'從 ... 以來');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('64', N'指考', N'102', N'warm up', N'暖⾝');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('65', N'指考', N'101', N'so much as', N'甚⾄於');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('66', N'指考', N'101', N'as well as', N'以及');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('67', N'指考', N'101', N'in spite of', N'儘管');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('68', N'指考', N'101', N'on behalf of', N'代表');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('69', N'指考', N'101', N'in this regard', N'關於 ; 在這點上');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('70', N'指考', N'101', N'one on one', N'⼀對⼀');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('71', N'指考', N'101', N'on one''s own', N'獨⾃');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('72', N'指考', N'101', N'by and large', N'⼤體上 ; 總體上');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('73', N'指考', N'101', N'opposed to', N'反對');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('74', N'指考', N'101', N'fight over', N'爭奪 ; 為 ... 爭吵');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('75', N'指考', N'101', N'battle for', N'為 …… 鬥爭');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('76', N'指考', N'101', N'compete against', N'與 ... 競爭');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('77', N'指考', N'101', N'head for', N'朝 ... 前進');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('78', N'指考', N'101', N'back up', N'備份');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('79', N'指考', N'101', N'call out', N'⼤聲地喊');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('80', N'指考', N'101', N'pass on', N'放棄');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('81', N'指考', N'100', N'at fault', N'有責任 ; 有錯');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('82', N'指考', N'100', N'on call', N'待命');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('83', N'指考', N'100', N'in tears', N'哭泣');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('84', N'指考', N'100', N'off guard', N'毫無防備');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('85', N'指考', N'100', N'by and large', N'總體上，⼀般來說');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('86', N'指考', N'100', N'over and over', N'⼀遍⼜⼀遍');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('87', N'指考', N'100', N'as usual', N'照例 ; 照常');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('88', N'指考', N'100', N'in some cases', N'在某些情況下');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('89', N'指考', N'100', N'to be frank', N'老實說');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('90', N'指考', N'100', N'with the help of', N'在 ... 的幫助下');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('91', N'指考', N'100', N'in the presence of', N'當著 ... 的⾯');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('92', N'指考', N'100', N'on top of', N'除 ... 之外');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('93', N'指考', N'100', N'in place of', N'代替');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('94', N'學測', N'111', N'contrary to', N'與 ... 相反');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('95', N'學測', N'111', N'except for', N'除了 ... 以外');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('96', N'學測', N'111', N'more of', N'更⼤程度上的 ; 更多的');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('97', N'學測', N'111', N'other than', N'⽽不 ...');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('98', N'學測', N'111', N'call for', N'需要 ; 值得 ; 應該');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('99', N'學測', N'111', N'try out', N'參加 ( 運動隊的 ) 選拔 ; 參加 ( 劇組的 ) 試演');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('100', N'學測', N'110', N'set up', N'設置');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('101', N'學測', N'110', N'hang on', N'等⼀下');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('102', N'學測', N'110', N'take over', N'接管 ; 繼任');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('103', N'學測', N'110', N'break down', N'故障 ;分解 ;崩潰');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('104', N'學測', N'110', N'come after', N'窮追不捨 ; 追趕');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('105', N'學測', N'110', N'get over', N'克服');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('106', N'學測', N'110', N'hold on to', N'抓住 ; 緊握');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('107', N'學測', N'110', N'watch out for', N'密切注意 ; 關注');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('108', N'學測', N'109', N'carry away', N'使 … 忘形 ; 使 ( 興奮得 ) 失去控制');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('109', N'學測', N'109', N'build on', N'建立在 .. 基礎上');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('110', N'學測', N'109', N'cope with', N'處理');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('111', N'學測', N'109', N'get off', N'離開');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('112', N'學測', N'109', N'as a result of', N'由於');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('113', N'學測', N'109', N'in a search for', N'尋找');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('114', N'學測', N'109', N'with a view to', N'⽬的是 ; 為了');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('115', N'學測', N'109', N'to the extent of', N'到了 ... 的程度');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('116', N'學測', N'109', N'shoot out', N'射出 ; 噴出');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('117', N'學測', N'109', N'hold on', N'等⼀下');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('118', N'學測', N'109', N'come across', N'碰到');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('119', N'學測', N'109', N'give up', N'放棄');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('120', N'學測', N'109', N'as for', N'⾄於');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('121', N'學測', N'109', N'owing to', N'因為 ; 由於');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('122', N'學測', N'109', N'in spite of', N'儘管');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('123', N'學測', N'109', N'with respect to', N'關於');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('124', N'學測', N'109', N'break down', N'故障 ;分解 ;崩潰');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('125', N'學測', N'109', N'mix up', N'混合');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('126', N'學測', N'109', N'tear off', N'撕掉 ; 脫掉');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('127', N'學測', N'109', N'result in', N'造成 ; 導致');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('128', N'學測', N'108', N'lead to', N'導致');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('129', N'學測', N'108', N'bring out', N'使出現 ; 使顯⽰');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('130', N'學測', N'108', N'stem from', N'源於');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('131', N'學測', N'108', N'come across', N'遇到 ; 碰到');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('132', N'學測', N'108', N'come to an end', N'結束 ; 終⽌');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('133', N'學測', N'108', N'go to great lengths', N'竭盡全⼒ ; 全⼒以赴');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('134', N'學測', N'108', N'put in service', N'啟⽤服務 ; 投入使⽤');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('135', N'學測', N'108', N'hold in store', N'存放 ; 等待');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('136', N'學測', N'108', N'bring along', N'帶來 ; 攜帶');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('137', N'學測', N'108', N'turn out', N'結果是 …');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('138', N'學測', N'108', N'account for', N'佔 ( 在數量上 );說明 ; 解釋');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('139', N'學測', N'108', N'serve as', N'充當 ; 當作');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('140', N'學測', N'108', N'due to', N'因為');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('141', N'學測', N'108', N'nothing but', N'只是 ; 只有');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('142', N'學測', N'108', N'in contrast to', N'與 … 相反');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('143', N'學測', N'108', N'on behalf of', N'代表');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('144', N'學測', N'107', N'refer to', N'提到 ; 提及 ;參考');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('145', N'學測', N'107', N'answer for', N'對 ( 某事物 ) 負責');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('146', N'學測', N'107', N'take part in', N'參加 ; 出席');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('147', N'學測', N'107', N'put up with', N'容忍 ; 忍受');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('148', N'學測', N'107', N'get away with', N'做（錯事）⽽未被懲罰');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('149', N'學測', N'107', N'clean up after', N'解決 … 製造的問題');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('150', N'學測', N'107', N'run out of', N'⽤完 ; 耗盡');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('151', N'學測', N'107', N'look down upon', N'輕視 ; ⼩看');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('152', N'學測', N'107', N'related to', N'與  ... 相關');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('153', N'學測', N'107', N'aside from', N'besides 除此之外 ( 包含 );except for 除了 … 之外 ( 不包含 )');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('154', N'學測', N'107', N'more than', N'超過 ; 比 … 更多');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('155', N'學測', N'107', N'nothing but', N'只是 ; 只有');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('156', N'學測', N'107', N'in other words', N'換句話說');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('157', N'學測', N'107', N'by no means', N'絕不 ; ⼀點都不');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('158', N'學測', N'107', N'at any cost', N'無論如何 ; 不計代價');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('159', N'學測', N'107', N'on the contrary', N'反之');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('160', N'學測', N'107', N'such as', N'如 ; 例如');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('161', N'學測', N'107', N'regardless of', N'不管 ; 不顧');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('162', N'學測', N'107', N'with respect to', N'關於');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('163', N'學測', N'107', N'on behalf of', N'代表');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('164', N'學測', N'106', N'check out', N'去查看 …; 去了解 … 的情況');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('165', N'學測', N'106', N'look into', N'凝視 ;調查 ; 研究');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('166', N'學測', N'106', N'watch over', N'保護 ; 照顧');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('167', N'學測', N'106', N'see through', N'看穿 ; 識破');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('168', N'學測', N'106', N'except for', N'除了 ... 以外');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('169', N'學測', N'106', N'be provided with', N'提供');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('170', N'學測', N'106', N'far from', N'遠離 ; 遠遠不');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('171', N'學測', N'106', N'let alone', N'更不必說');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('172', N'學測', N'106', N'get done', N'結束 ; 完成');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('173', N'學測', N'106', N'get lost', N'滾開');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('174', N'學測', N'106', N'make do', N'湊合著⽤');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('175', N'學測', N'106', N'make believe', N'假裝');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('176', N'學測', N'106', N'at most', N'⾄多');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('177', N'學測', N'106', N'in contrast', N'相反地');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('178', N'學測', N'106', N'out of', N'在 … 之外');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('179', N'學測', N'106', N'as well as', N'以及');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('180', N'學測', N'106', N'in case of', N'以防萬⼀');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('181', N'學測', N'106', N'due to', N'因為');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('182', N'學測', N'106', N'break off', N'中斷 ; 中⽌');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('183', N'學測', N'106', N'approve of', N'贊成 ; 同意');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('184', N'學測', N'106', N'engage in', N'參加 ; 參與');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('185', N'學測', N'106', N'take over', N'接管 ; 繼任');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('186', N'學測', N'105', N'make believe', N'假裝');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('187', N'學測', N'105', N'get along', N'相處融洽 ; 和睦相處');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('188', N'學測', N'105', N'turn out', N'結果是');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('189', N'學測', N'105', N'feel like', N'想要做某事 ; 想要某物');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('190', N'學測', N'105', N'hold on to', N'保留 ; 保存');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('191', N'學測', N'105', N'get rid of', N'擺脫 ; 去除');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('192', N'學測', N'105', N'make fun of', N'嘲弄 ; 取笑');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('193', N'學測', N'105', N'take advantage of', N'利⽤ ; 佔便宜');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('194', N'學測', N'105', N'to the point', N'中肯 ; 恰當');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('195', N'學測', N'105', N'on the rise', N'在上升 ; 在增加');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('196', N'學測', N'105', N'off the hook', N'脫離困境 ; 脫⾝');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('197', N'學測', N'105', N'for the record', N'特此強調 ; 鄭重聲明');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('198', N'學測', N'103', N'set out', N'開始 ; 著⼿');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('199', N'學測', N'103', N'turn out', N'結果是');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('200', N'學測', N'103', N'put into practice', N'實踐 ; 執⾏');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('201', N'學測', N'103', N'take into account', N'考慮到 ; 顧及');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('202', N'學測', N'102', N'in fact', N'事實上');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('203', N'學測', N'102', N'at the same time', N'同時');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('204', N'學測', N'102', N'on the other hand', N'另⼀⽅⾯');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('205', N'學測', N'102', N'composed of', N'由 ... 組成的');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('206', N'學測', N'102', N'based on', N'以 … 為基礎 ; 基於 …');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('207', N'學測', N'102', N'result in', N'造成 ; 導致');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('208', N'學測', N'102', N'fight against', N'與 … 鬥爭');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('209', N'學測', N'101', N'in fact', N'事實上');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('210', N'學測', N'101', N'once again', N'再⼀次');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('211', N'學測', N'101', N'as usual', N'⼀如往常');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('212', N'學測', N'101', N'for instance', N'例如');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('213', N'學測', N'101', N'look for', N'尋找');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('214', N'學測', N'101', N'get over', N'恢復正常 ; 克服');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('215', N'學測', N'101', N'do without', N'沒有也⾏');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('216', N'學測', N'101', N'bump into', N'巧遇');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('217', N'學測', N'101', N'skip over', N'跳過');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('218', N'學測', N'101', N'come across', N'遇到 ; 碰到');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('219', N'學測', N'101', N'look into', N'凝視 ;調查 ; 研究');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('220', N'學測', N'101', N'break down', N'故障 ;分解 ;崩潰');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('221', N'學測', N'100', N'go through', N'經歷');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('222', N'學測', N'100', N'make up', N'編造 ;組成 ;和好 ;補償');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('223', N'學測', N'100', N'change into', N'改變 ; 變化');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('224', N'學測', N'100', N'turn out', N'結果是');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('225', N'學測', N'100', N'appeal to', N'吸引');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('226', N'學測', N'100', N'be presented with', N'獲贈');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('227', N'學測', N'100', N'result in', N'造成 ; 導致');
INSERT INTO phrase_test (Orders, Test, Year, Phrase, Chinese) VALUES ('228', N'學測', N'100', N'bring about', N'造成 ; 引起');
