CREATE TABLE phrase_all 
(
    Orders	int,
    Phrase	nvarchar(300),
    Chinese	nvarchar(300)
);

INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('1', N'be about to do something', N'即將，將要做某事');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('2', N'by accident', N'偶然地，意外地');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('3', N'in accord (with . . . )', N'與…一致，融洽');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('4', N'on account of . . .', N'因為 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('5', N'act on something', N'根據某物行事');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('6', N'in addition (to . . . )', N'除…之外 (還)');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('7', N'aside from . . .', N'除了 …以外 (還有 …)；除了 …以外');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('8', N'in advance (of something)', N'(在…)之前，事先');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('9', N'take advantage of . . .', N'利用 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('10', N'after all', N'畢竟');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('11', N'along with . . .', N'與…一起，除了 …之外');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('12', N'along . . . lines', N'以…的方式');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('13', N'amount to something', N'總計 …，總數達到 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('14', N'with open arms', N'熱情地，熱烈地');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('15', N'as for . . .', N'至於 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('16', N'back up . . .', N'支持 …，證實 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('17', N'base something on something', N'以…為根據，以 …為基礎');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('18', N'on behalf of someone', N'代表某人');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('19', N'belong to . . .', N'是…一類；屬於 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('20', N'best of all', N'最令人高興的是，最棒的是');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('21', N'beyond  belief', N'令人難以置信');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('22', N'believe it or not', N'信不信由你');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('23', N'black out something', N'封鎖  (資訊、消息等 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('24', N'bless you', N'保佑你 (對打噴嚏者所說的話 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('25', N'be blessed with something', N'有幸享有 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('26', N'take a bow', N'謝幕，鞠躬答謝');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('27', N'break down (something)', N'使(…)分解');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('28', N'break out', N'爆發，突然發生');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('29', N'break out (of something)', N'逃離  (某事物 )，擺脫  (某事物 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('30', N'give someone  a break  (infml. )', N'饒了、放過某人');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('31', N'breathe  in', N'吸氣');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('32', N'bring about something', N'導致 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('33', N'bring . . . back', N'使…恢復');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('34', N'bring something on . . .', N'給…招來 (壞事 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('35', N'bring down someone', N'擊敗 …，推翻 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('36', N'bring someone to justice', N'將…繩之以法，把 …緝捕歸案');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('37', N'build on something', N'以某事物為基礎');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('38', N'burn down (something)', N'(被)燒毀 (…)');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('39', N'bury oneself in something', N'埋首於某事');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('40', N'nothing but', N'只有');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('41', N'can’t help but do something', N'忍不住 …，無法克制 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('42', N'buy into something  (infml.)', N'相信 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('43', N'call for something', N'呼籲…，公開要求 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('44', N'care for someone', N'照顧、照料某人');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('45', N'couldn’t  care less (infml .)', N'毫不在乎');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('46', N'carry  out something', N'實行某事，進行某事');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('47', N'cast a spell on someone', N'對…下咒，對 …施魔法');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('48', N'cast out . . .', N'驅逐 …，趕走 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('49', N'cater to . . .', N'滿足 …，迎合 …的需求');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('50', N'on the off chance', N'碰運氣');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('51', N'check out . . .', N'查看 …，檢查 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('52', N'clear up something', N'解決 (疑慮、問題等 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('53', N'close  out something', N'結束某事');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('54', N'come upon . . .', N'偶然遇見 …，偶然發現 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('55', N'come off', N'脫落');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('56', N'come from something', N'來自 …，起源於 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('57', N'come across', N'使人產生 (…的)印象');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('58', N'come along', N'抵達，出現');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('59', N'come up with something', N'想出，提出 (計畫、答案等 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('60', N'remember the new  words.  when it comes to (doing) something', N'說到、提及 (做)某事');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('61', N'have something in common', N'(和某人的想法、興趣等方面 )有共同之； (和某物或某處的特點 )有相同、相似之處');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('62', N'something can’t/doesn’t compare (with something else)', N'不能  (與某事) 相比');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('63', N'in comparison (with . . . )', N'(與…)相比較');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('64', N'consist of . . .', N'由…組成、構成');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('65', N'in control', N'保持冷靜，處之泰然；掌控，操控 (機構或局勢 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('66', N'cost someone dearly', N'使某人付出沉重代價');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('67', N'cover up something', N'掩飾，掩蓋 (錯誤、罪行等 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('68', N'crowd into something', N'大量湧入某處，大批擠進某處');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('69', N'crowd out . . .', N'排擠 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('70', N'cut down  (on something)', N'減少 (…)');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('71', N'dawn on someone', N'使某人開始明白');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('72', N'these days  (infml.)', N'現今，如今');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('73', N'"day in, day out"', N'日復一日');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('74', N'day after day', N'每天，一天天');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('75', N'around the clock  = all day and all night', N'日以繼夜');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('76', N'deal with something', N'處理 …，解決 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('77', N'a great deal of something', N'大量的某物');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('78', N'depend on . . .', N'依賴 …，依靠 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('79', N'rely on . . .', N'(為生活、生存 )依賴 …；信賴 …，信任 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('80', N'derive something from something', N'從…中獲得 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('81', N'deprive . . . of something', N'從…剝奪某物，使 …失去某物');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('82', N'die off', N'相繼死去');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('83', N'be dying to do something  (infml.)', N'很想、渴望做某事');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('84', N'in the dead of night', N'夜深人靜時');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('85', N'dig in (infml. )', N'開動');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('86', N'dig into something', N'探究某事');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('87', N'dish out something', N'分配某物');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('88', N'without a doubt', N'毫無疑問地');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('89', N'drive off', N'(駕駛 )駕車離去， (車輛 )開走');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('90', N'drive . . . out', N'驅離 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('91', N'drop out (of something)', N'退出 (學校或活動 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('92', N'due to . . .', N'因為 …，由於 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('93', N'on duty', N'值班，值勤');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('94', N'at ease', N'感到自在、輕鬆的');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('95', N'end up (doing something)', N'最後處於 (…)，結果成為 (…)');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('96', N'engage in something', N'參加 …，從事 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('97', N'even though', N'即使，雖然');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('98', N'to . . . extent', N'到達 …的程度');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('99', N'go to extremes', N'採取極端的手段');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('100', N'in someone’s  eyes', N'在某人看來，在某人心目中');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('101', N'have one’s eye on someone', N'看上 …，看中 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('102', N'open one’s eyes (to something)', N'使某人 (對…)開眼界、長見識');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('103', N'save (one’s) face', N'(給…)留面子');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('104', N'disappear off the face of the earth', N'消失得無影無蹤');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('105', N'in fact', N'實際上，事實上');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('106', N'as a matter of fact', N'實際上，其實');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('107', N'in reality', N'事實上');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('108', N'fade out', N'使(畫面 )淡出，使 (聲音 )漸弱');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('109', N'far from (doing) something', N'完全不 …，根本不 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('110', N'be on one’s feet', N'久站');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('111', N'fight off something', N'擊退 …，克服 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('112', N'nowhere to be found', N'找不到');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('113', N'first of all', N'第一，首先');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('114', N'come first', N'最為重要，擺在第一位');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('115', N'first and foremost', N'首先，首要的是');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('116', N'fit in', N'適應');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('117', N'flash back (to something)', N'回想起  (某事 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('118', N'forgive and forget', N'完全原諒，不念舊惡');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('119', N'to the fullest', N'充分地');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('120', N'get out of something', N'逃避 …，擺脫 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('121', N'get into something', N'養成某種習慣');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('122', N'get behind (with something)', N'(在…方面 )落後');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('123', N'get over  . . .', N'從…中恢復常態');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('124', N'get rid of . . .', N'擺脫…，除掉 …；丟棄 …，扔掉 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('125', N'get around', N'四處走動，旅行； (消息、訊息等 ) 傳開，流傳');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('126', N'get away (from . . . )', N'(從…)離開， (從…)逃離');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('127', N'get at  something', N'查明 …，瞭解 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('128', N'at first glance', N'乍看之下，初見');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('129', N'at a (single) glance', N'看一眼');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('130', N'be glued to something  (infml.)', N'全神貫注地看著 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('131', N'go on', N'發生，進行');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('132', N'go on to do something', N'(完成某事後 ) 接著做另一件事');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('133', N'go to . . .', N'給予 …，由 …得到');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('134', N'go by', N'(時間 )流逝');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('135', N'go by something', N'遵循某事物，遵從某事物');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('136', N'go beyond something', N'超出 …，超過 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('137', N'take . . . for granted', N'將…視為理所當然');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('138', N'grow out of something', N'產生於 …，源自於 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('139', N'on the other hand', N'另一方面');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('140', N'in the hands of someone', N'受…控制');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('141', N'come in handy', N'有用，派上用場');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('142', N'hang up', N'掛斷 (電話 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('143', N'hang out (with someone)', N'(與…)閒晃、廝混');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('144', N'have no idea', N'不知道，不瞭解');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('145', N'have no need of something', N'不需要某物');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('146', N'have nothing to do with . . .', N'與…無關');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('147', N'as luck would have it', N'幸而，碰巧');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('148', N'had better', N'最好 …，還是 (做)…好');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('149', N'make  (the)  headlines :', N'成為重要新聞、頭條');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('150', N'pour out one’s heart', N'傾訴，傾吐');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('151', N'win the heart of someone', N'贏得 …的心');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('152', N'lose one’s heart (to someone)', N'愛上 (某人 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('153', N'open one’s heart (to someone)', N'(向某人 ) 敞開心扉');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('154', N'one’s heart is in one’s mouth', N'提心吊膽， 緊張害怕');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('155', N'hit it big  (infml. )', N'成功');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('156', N'hit the roof (infml. )', N'勃然大怒，生氣');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('157', N'hit home', N'使(某人 )深切感受到');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('158', N'at home', N'自在，無拘無束');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('159', N'in honor of . . .', N'向…致敬');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('160', N'hunt someone down', N'追捕某人，追緝某人');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('161', N'for instance  = for example', N'例如');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('162', N'keep ( . . . ) out (of something)', N'不使 (…)進入 (某地 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('163', N'keep (someone) out of something', N'使(某人 )不捲入 …，使 (某人 )不受 …影響');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('164', N'keep off something', N'避免吃某物');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('165', N'keep down something', N'抑制某物增長，使某物不增加');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('166', N'keep up with . . .', N'跟上 …，趕上 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('167', N'keep . . . in mind', N'記住 …，考慮 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('168', N'knock on wood', N'敲木頭 (希望留住好運、避免厄運時說的話 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('169', N'know no bounds', N'無窮無盡');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('170', N'lay down something', N'制定，明訂 (規定或法律等 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('171', N'at least', N'至少，起碼；至少，不少於');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('172', N'last but not least', N'最後但同樣重要地');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('173', N'leave something alone', N'別動、別碰某物');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('174', N'lend oneself to something', N'適合某事物，適用於某事物');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('175', N'let us say', N'比方說，例如');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('176', N'come to life', N'活過來');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('177', N'take someone’s  life', N'殺死某人，取某人性命');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('178', N'live with something', N'忍受某事物');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('179', N'live up to something', N'達到 (期待 )，履行  (諾言 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('180', N'live on something', N'以某食維生');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('181', N'see the light', N'終於明白、領悟');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('182', N'before long', N'不久之後，很快');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('183', N'as long as', N'只要');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('184', N'no longer', N'不再');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('185', N'look for . . .', N'尋找 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('186', N'look up something', N'查閱 …，搜尋 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('187', N'look into something', N'調查 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('188', N'look around (something)', N'參訪 (某地 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('189', N'look someone up and down', N'(批判性地 )打量某人');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('190', N'look forward to (doing) something', N'高興地期待、盼望  (做) 某事');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('191', N'make  for something', N'導致某事，促成某事');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('192', N'make friends (with someone)', N'(和…)交朋友');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('193', N'make fun of . . .', N'嘲笑 …，取笑 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('194', N'make it', N'及時趕到');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('195', N'make up something', N'編造 (藉口、謊言等 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('196', N'make up something', N'組成 …，構成 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('197', N'make up one’s mind', N'下定決心');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('198', N'keep an open mind', N'不懷成見，願意聽取他人的意見');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('199', N'make peace (with someone)', N'(與某人 )談和');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('200', N'make oneself understood', N'把自己的意思表達清楚');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('201', N'many a(n)', N'大量，許多');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('202', N'in the meantime', N'在此時，期間');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('203', N'not to mention something', N'更不用說 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('204', N'mistake . . . for . . .', N'把…誤認為 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('205', N'what is more', N'再者，而且');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('206', N'no more than', N'僅僅');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('207', N'more often than not  = usually', N'多半，往往');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('208', N'move  on (to something)', N'接著進行 (不同的事 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('209', N'occur to someone', N'某人想到 …，想起 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('210', N'once again', N'再一次');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('211', N'all at once', N'突然');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('212', N'only if', N'唯若 …才，只有當');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('213', N'open up', N'暢所欲言，開誠布公');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('214', N'on the outside', N'表面上，由外表看來');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('215', N'over and over (again)', N'再三地，一再地');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('216', N'owing  to something', N'因為某事');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('217', N'take part in something', N'參加 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('218', N'play a part (in something)', N'參與 (…)，對 (…)有影響');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('219', N'pass away', N'去世，過世');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('220', N'pass on something (to someone)', N'傳遞某物 (給某人 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('221', N'pay off', N'成功，有所回報');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('222', N'pay someone back (s th.)', N'償還某人 (人情、恩惠 )；償還某人 (金錢 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('223', N'two peas in a pod', N'一模一樣');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('224', N'every penny', N'每一分錢，所有的錢');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('225', N'pick up something', N'撿起 …，拿起 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('226', N'pick up something', N'(偶然 )得到 …，學會 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('227', N'in place of . . .', N'代替 …，取代 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('228', N'take the place of . . .', N'代替 …，頂替 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('229', N'pluck up the courage (to do something)', N'鼓起勇氣 (…)');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('230', N'pop the question  (infml.)', N'求婚');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('231', N'in preference to . . .', N'而非 …，並非 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('232', N'in one’s presence', N'在某人面前');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('233', N'press  for something', N'不停要求某事物，持續要求某事物');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('234', N'pull up (something)', N'(駕駛 )停車， (車輛 )停止');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('235', N'put on something', N'塗抹某物；穿戴某物');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('236', N'put up with . . .', N'忍受 …，容忍 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('237', N'put off (doing) something', N'拖延 …，延宕 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('238', N'put aside something', N'儲存某物，保留某物');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('239', N'rather than', N'而不是');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('240', N'would rather . . . (than . . . )', N'寧願 …，寧可 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('241', N'reach out to someone', N'向…伸出援手，對 …提供援助');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('242', N'read (something) into something', N'(對某事 ) 過度解釋、解讀');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('243', N'the recesses of something', N'(某物的 ) 隱蔽處； (情感、思想的 ) 深處');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('244', N'refer to . . . as something', N'將…稱作某物');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('245', N'result in something', N'導致 …，造成 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('246', N'in return (for something)', N'作為  (對某事的 ) 回報');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('247', N'revenge oneself on someone', N'向某人報復，對某人報仇');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('248', N'ring out', N'(聲音 ) 響亮，清晰可聞');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('249', N'at risk of (doing) something', N'有(遭逢 )某事的危險');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('250', N'roll down something', N'搖下 (車窗 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('251', N'round up . . .', N'圍捕 …；將 …聚集起來');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('252', N'run into something', N'遭遇 (困難、麻煩等 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('253', N'second to none', N'不亞於，首屈一指');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('254', N'make sense', N'合乎情理，明智；說得通，易於理解');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('255', N'set up something', N'設立 …，創立 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('256', N'set out', N'出發，啟程； (懷著目標 )開始工作');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('257', N'settle down', N'定居下來');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('258', N'settle a/the score (with sb. )', N'報復  (某人 )，(和某人 ) 算帳');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('259', N'nowhere in sight', N'看不到，找不到');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('260', N'sit back', N'不採取行動，袖手旁觀');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('261', N'size up . . .', N'評估 …，判斷 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('262', N'and so on', N'諸如此類，等等');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('263', N'or so', N'大約');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('264', N'sleep in', N'晚起，睡懶覺');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('265', N'sow the seeds of something', N'播下 …的種子，成為 …的肇端');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('266', N'spare one’s feelings', N'不使某人難過，顧及某人的感受');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('267', N'spice up something', N'為某物增添趣味');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('268', N'in spite of something', N'儘管 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('269', N'on the spot', N'當下，立刻');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('270', N'stay up', N'熬夜，不睡覺');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('271', N'steep oneself in something', N'沉浸於 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('272', N'stem from something', N'起源於某事物，由某事物引起');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('273', N'stick to something', N'維持 …，堅持 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('274', N'stir up something', N'挑起 …，煽動 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('275', N'stop by ( . . . )', N'順路拜訪  (…)');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('276', N'strike a balance (between . . . and . . . )', N'求得平衡，折衷');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('277', N'for sure  (infml.)', N'肯定，一定');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('278', N'be supposed to', N'(依規定、安排等 )應當，該；一般認為');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('279', N'swarm with . . .', N'擠滿 …，到處是 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('280', N'sweep away something', N'徹底消除 …，消滅 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('281', N'take on something', N'接受  (工作 )，承擔  (責任 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('282', N'take flight', N'逃走');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('283', N'take root', N'(思想 ) 深入人心； (植物 ) 生根');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('284', N'take its toll (on . . . )', N'(對…)產生不良影響 、造成重大 損失');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('285', N'the talk of something', N'(某地 )人人談論的話題');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('286', N'tear apart something', N'拆散某物，使某物分崩離析');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('287', N'in the long  term', N'從長期來看');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('288', N'"the long term, i t may lead to eating disorders . thanks to . . ."', N'幸虧 …，由於 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('289', N'that is (to say)', N'意即，也就是說');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('290', N'think of . . .', N'為…著想、設想；想到 …，構思出 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('291', N'think  of . . . as . . .', N'把…看作 …，將 …視為 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('292', N'think twice (about doing sth.)', N'三思而行，仔細考慮 (…)');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('293', N'have second thoughts', N'(經過考慮後 )改變主意，改變想法');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('294', N'food for thought', N'引人深思的事物');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('295', N'be tickled pink', N'非常開心、高興');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('296', N'(someone) be tied up', N'(某人 )非常忙碌、無法分身');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('297', N'in time', N'及時，來得及');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('298', N'at a time', N'每次，一次');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('299', N'at times : from time to time', N'有時候，偶爾');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('300', N'all the time', N'一直，始終；經常');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('301', N'from time to time', N'偶爾，有時');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('302', N'on occasion', N'偶爾，不時');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('303', N'(every) once in a while', N'偶爾，有時候');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('304', N'(every)  now and then', N'偶爾');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('305', N'time after time', N'一再地，再三地');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('306', N'kill time', N'打發時間，消磨時光');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('307', N'in the course of time  = eventually', N'總有一天，最終');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('308', N'together with . . .', N'連同 …，和 …一起');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('309', N'lose touch (with . . . )', N'(與…)失去聯繫');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('310', N'on the right  track', N'依循正確的方式');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('311', N'track down . . .', N'(經長時間 )追蹤到 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('312', N'true to life', N'逼真，寫實的');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('313', N'tuck someone in', N'替某人蓋被子');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('314', N'turn off something', N'關掉 (電源、水等 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('315', N'turn to . . .', N'求助於 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('316', N'turn into . . .', N'變成…');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('317', N'turn out', N'發展為，結果是');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('318', N'turn  down  . . .', N'拒絕 …，回絕 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('319', N'turn up', N'(出其不意地 )出現');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('320', N'up to something', N'(數量、程度等 )至多可達 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('321', N'be (of) no use', N'沒有用，無用');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('322', N'make use of . . .', N'利用 …，使用 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('323', N'what’s the use (of doing something)', N'(做某事 )沒有意義、用處');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('324', N'put (something) to (good) use', N'有效利用 (某物 )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('325', N'as usual', N'一如往常地');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('326', N'with a view to (doing) something', N'為了 …，以 …為目的');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('327', N'point of view', N'觀點');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('328', N'can’t wait', N'迫不及待');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('329', N'wait for their winter vacation to  begin.  warm  up', N'變暖，暖和起來');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('330', N'warn someone off (something)', N'告誡某人不要 …');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('331', N'by the way  (infml.)', N'順帶一提');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('332', N'in no way', N'一點也不');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('333', N'on the way', N'(嬰兒 )尚未出生；即將到來，就要發生');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('334', N'in some ways', N'某種程度上');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('335', N'have a way of doing something  …', N'是常有的事，有 …的習慣');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('336', N'go a long way toward doing something', N'對做某事有幫助');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('337', N'wear away (something)', N'磨損 (…)as well (as . . . )');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('338', N'would do well to do something', N'建議 (做…)，應該 …比較好');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('339', N'"what if . . .  = what would happen, if…"', N'要是 …會怎麼樣');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('340', N'on the whole', N'大體上來說，大致而言');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('341', N'wipe up (something)', N'擦拭 (…)，抹掉 (…)');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('342', N'no wonder =  it is no wonder that', N'難怪');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('343', N'in other  words', N'換句話說');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('344', N'be lost for words', N'(因驚訝、難過等 ) 說不出話，無言');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('345', N'work out', N'成功地發展');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('346', N'work on something', N'致力於某事');
INSERT INTO phrase_all (Orders, Phrase, Chinese) VALUES ('347', N'be worried sick', N'極度擔心');
