CREATE TABLE phrase_gsat (
    Orders int,
    Year nvarchar(300),
    Phrase nvarchar(300) primary key,
    Chinese	nvarchar(300),
    Unit nvarchar(300)
);

INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('1', N'108', N'account for', N'佔 ( 在數量上 );說明 ; 解釋', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('2', N'107', N'answer for', N'對 ( 某事物 ) 負責', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('3', N'100', N'appeal to', N'吸引', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('4', N'106', N'approve of', N'贊成 ; 同意', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('5', N'109', N'as a result of', N'由於', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('6', N'109', N'as for', N'⾄於', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('7', N'101', N'as usual', N'⼀如往常', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('8', N'106', N'as well as', N'以及', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('9', N'107', N'aside from', N'besides 除此之外 ( 包含 );except for 除了 … 之外 ( 不包含 )', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('10', N'107', N'at any cost', N'無論如何 ; 不計代價', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('11', N'106', N'at most', N'⾄多', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('12', N'102', N'at the same time', N'同時', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('13', N'102', N'based on', N'以 … 為基礎 ; 基於 …', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('14', N'100', N'be presented with', N'獲贈', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('15', N'106', N'be provided with', N'提供', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('16', N'110', N'break down', N'故障 ;分解 ;崩潰', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('17', N'106', N'break off', N'中斷 ; 中⽌', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('18', N'100', N'bring about', N'造成 ; 引起', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('19', N'108', N'bring along', N'帶來 ; 攜帶', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('20', N'108', N'bring out', N'使出現 ; 使顯⽰', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('21', N'109', N'build on', N'建立在 .. 基礎上', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('22', N'101', N'bump into', N'巧遇', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('23', N'107', N'by no means', N'絕不 ; ⼀點都不', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('24', N'111', N'call for', N'需要 ; 值得 ; 應該', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('25', N'109', N'carry away', N'使 … 忘形 ; 使 ( 興奮得 ) 失去控制', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('26', N'100', N'change into', N'改變 ; 變化', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('27', N'106', N'check out', N'去查看 …; 去了解 … 的情況', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('28', N'107', N'clean up after', N'解決 … 製造的問題', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('29', N'109', N'come across', N'碰到', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('30', N'110', N'come after', N'窮追不捨 ; 追趕', N'Unit 01');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('31', N'108', N'come to an end', N'結束 ; 終⽌', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('32', N'102', N'composed of', N'由 ... 組成的', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('33', N'111', N'contrary to', N'與 ... 相反', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('34', N'109', N'cope with', N'處理', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('35', N'101', N'do without', N'沒有也⾏', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('36', N'108', N'due to', N'因為', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('37', N'106', N'engage in', N'參加 ; 參與', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('38', N'111', N'except for', N'除了 ... 以外', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('39', N'106', N'far from', N'遠離 ; 遠遠不', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('40', N'105', N'feel like', N'想要做某事 ; 想要某物', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('41', N'102', N'fight against', N'與 … 鬥爭', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('42', N'101', N'for instance', N'例如', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('43', N'105', N'for the record', N'特此強調 ; 鄭重聲明', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('44', N'105', N'get along', N'相處融洽 ; 和睦相處', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('45', N'107', N'get away with', N'做（錯事）⽽未被懲罰', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('46', N'106', N'get done', N'結束 ; 完成', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('47', N'106', N'get lost', N'滾開', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('48', N'109', N'get off', N'離開', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('49', N'110', N'get over', N'克服', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('50', N'105', N'get rid of', N'擺脫 ; 去除', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('51', N'109', N'give up', N'放棄', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('52', N'100', N'go through', N'經歷', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('53', N'108', N'go to great lengths', N'竭盡全⼒ ; 全⼒以赴', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('54', N'110', N'hang on', N'等⼀下', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('55', N'108', N'hold in store', N'存放 ; 等待', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('56', N'109', N'hold on', N'等⼀下', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('57', N'110', N'hold on to', N'抓住 ; 緊握', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('58', N'109', N'in a search for', N'尋找', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('59', N'106', N'in case of', N'以防萬⼀', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('60', N'106', N'in contrast', N'相反地', N'Unit 02');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('61', N'108', N'in contrast to', N'與 … 相反', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('62', N'102', N'in fact', N'事實上', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('63', N'107', N'in other words', N'換句話說', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('64', N'109', N'in spite of', N'儘管', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('65', N'108', N'lead to', N'導致', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('66', N'106', N'let alone', N'更不必說', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('67', N'107', N'look down upon', N'輕視 ; ⼩看', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('68', N'101', N'look for', N'尋找', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('69', N'106', N'look into', N'凝視 ;調查 ; 研究', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('70', N'106', N'make believe', N'假裝', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('71', N'106', N'make do', N'湊合著⽤', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('72', N'105', N'make fun of', N'嘲弄 ; 取笑', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('73', N'100', N'make up', N'編造 ;組成 ;和好 ;補償', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('74', N'109', N'mix up', N'混合', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('75', N'111', N'more of', N'更⼤程度上的 ; 更多的', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('76', N'107', N'more than', N'超過 ; 比 … 更多', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('77', N'108', N'nothing but', N'只是 ; 只有', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('78', N'105', N'off the hook', N'脫離困境 ; 脫⾝', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('79', N'108', N'on behalf of', N'代表', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('80', N'107', N'on the contrary', N'反之', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('81', N'102', N'on the other hand', N'另⼀⽅⾯', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('82', N'105', N'on the rise', N'在上升 ; 在增加', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('83', N'101', N'once again', N'再⼀次', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('84', N'111', N'other than', N'⽽不 ...', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('85', N'106', N'out of', N'在 … 之外', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('86', N'109', N'owing to', N'因為 ; 由於', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('87', N'108', N'put in service', N'啟⽤服務 ; 投入使⽤', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('88', N'103', N'put into practice', N'實踐 ; 執⾏', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('89', N'107', N'put up with', N'容忍 ; 忍受', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('90', N'107', N'refer to', N'提到 ; 提及 ;參考', N'Unit 03');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('91', N'107', N'regardless of', N'不管 ; 不顧', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('92', N'107', N'related to', N'與  ... 相關', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('93', N'100', N'result in', N'造成 ; 導致', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('94', N'107', N'run out of', N'⽤完 ; 耗盡', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('95', N'106', N'see through', N'看穿 ; 識破', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('96', N'108', N'serve as', N'充當 ; 當作', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('97', N'103', N'set out', N'開始 ; 著⼿', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('98', N'110', N'set up', N'設置', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('99', N'109', N'shoot out', N'射出 ; 噴出', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('100', N'101', N'skip over', N'跳過', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('101', N'108', N'stem from', N'源於', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('102', N'107', N'such as', N'如 ; 例如', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('103', N'105', N'take advantage of', N'利⽤ ; 佔便宜', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('104', N'103', N'take into account', N'考慮到 ; 顧及', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('105', N'110', N'take over', N'接管 ; 繼任', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('106', N'107', N'take part in', N'參加 ; 出席', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('107', N'109', N'tear off', N'撕掉 ; 脫掉', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('108', N'109', N'to the extent of', N'到了 ... 的程度', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('109', N'105', N'to the point', N'中肯 ; 恰當', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('110', N'111', N'try out', N'參加 ( 運動隊的 ) 選拔 ; 參加 ( 劇組的 ) 試演', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('111', N'108', N'turn out', N'結果是 …', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('112', N'110', N'watch out for', N'密切注意 ; 關注', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('113', N'106', N'watch over', N'保護 ; 照顧', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('114', N'109', N'with a view to', N'⽬的是 ; 為了', N'Unit 04');
INSERT INTO phrase_gsat (Orders, Year, Phrase, Chinese, Unit) VALUES ('115', N'109', N'with respect to', N'關於', N'Unit 04');
