CREATE TABLE phrase_all (
    Orders int,
    Phrase nvarchar(300) primary key,
    Chinese	nvarchar(300),
    Unit nvarchar(300)
);

INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('1', N'a great deal of something', N'大量的某物', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('2', N'act on something', N'根據某物行事', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('3', N'after all', N'畢竟', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('4', N'all at once', N'突然', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('5', N'all the time', N'一直，始終；經常', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('6', N'along . . . lines', N'以…的方式', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('7', N'along with . . .', N'與…一起，除了 …之外', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('8', N'amount to something', N'總計 …，總數達到 …', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('9', N'and so on', N'諸如此類，等等', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('10', N'around the clock  = all day and all night', N'日以繼夜', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('11', N'as a matter of fact', N'實際上，其實', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('12', N'as for . . .', N'至於 …', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('13', N'as long as', N'只要', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('14', N'as luck would have it', N'幸而，碰巧', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('15', N'as usual', N'一如往常地', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('16', N'aside from . . .', N'除了 …以外 (還有 …)；除了 …以外', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('17', N'at a (single) glance', N'看一眼', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('18', N'at a time', N'每次，一次', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('19', N'at ease', N'感到自在、輕鬆的', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('20', N'at first glance', N'乍看之下，初見', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('21', N'at home', N'自在，無拘無束', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('22', N'at least', N'至少，起碼；至少，不少於', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('23', N'at risk of (doing) something', N'有(遭逢 )某事的危險', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('24', N'at times : from time to time', N'有時候，偶爾', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('25', N'back up . . .', N'支持 …，證實 …', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('26', N'base something on something', N'以…為根據，以 …為基礎', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('27', N'be (of) no use', N'沒有用，無用', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('28', N'be about to do something', N'即將，將要做某事', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('29', N'be blessed with something', N'有幸享有 …', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('30', N'be dying to do something  (infml.)', N'很想、渴望做某事', N'Unit 01');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('31', N'be glued to something  (infml.)', N'全神貫注地看著 …', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('32', N'be lost for words', N'(因驚訝、難過等 ) 說不出話，無言', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('33', N'be on one’s feet', N'久站', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('34', N'be supposed to', N'(依規定、安排等 )應當，該；一般認為', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('35', N'be tickled pink', N'非常開心、高興', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('36', N'be tied up', N'(某人 )非常忙碌、無法分身', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('37', N'be worried sick', N'極度擔心', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('38', N'before long', N'不久之後，很快', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('39', N'believe it or not', N'信不信由你', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('40', N'belong to . . .', N'是…一類；屬於 …', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('41', N'best of all', N'最令人高興的是，最棒的是', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('42', N'beyond  belief', N'令人難以置信', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('43', N'black out something', N'封鎖  (資訊、消息等 )', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('44', N'bless you', N'保佑你 (對打噴嚏者所說的話 )', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('45', N'break down (something)', N'使(…)分解', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('46', N'break out', N'爆發，突然發生', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('47', N'break out (of something)', N'逃離  (某事物 )，擺脫  (某事物 )', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('48', N'breathe  in', N'吸氣', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('49', N'bring . . . back', N'使…恢復', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('50', N'bring about something', N'導致 …', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('51', N'bring down someone', N'擊敗 …，推翻 …', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('52', N'bring someone to justice', N'將…繩之以法，把 …緝捕歸案', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('53', N'bring something on . . .', N'給…招來 (壞事 )', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('54', N'build on something', N'以某事物為基礎', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('55', N'burn down (something)', N'(被)燒毀 (…)', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('56', N'bury oneself in something', N'埋首於某事', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('57', N'buy into something  (infml.)', N'相信 …', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('58', N'by accident', N'偶然地，意外地', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('59', N'by the way  (infml.)', N'順帶一提', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('60', N'call for something', N'呼籲…，公開要求 …', N'Unit 02');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('61', N'can’t help but do something', N'忍不住 …，無法克制 …', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('62', N'can’t wait', N'迫不及待', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('63', N'care for someone', N'照顧、照料某人', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('64', N'carry  out something', N'實行某事，進行某事', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('65', N'cast a spell on someone', N'對…下咒，對 …施魔法', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('66', N'cast out . . .', N'驅逐 …，趕走 …', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('67', N'cater to . . .', N'滿足 …，迎合 …的需求', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('68', N'check out . . .', N'查看 …，檢查 …', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('69', N'clear up something', N'解決 (疑慮、問題等 )', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('70', N'close  out something', N'結束某事', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('71', N'come across', N'使人產生 (…的)印象', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('72', N'come along', N'抵達，出現', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('73', N'come first', N'最為重要，擺在第一位', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('74', N'come from something', N'來自 …，起源於 …', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('75', N'come in handy', N'有用，派上用場', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('76', N'come off', N'脫落', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('77', N'come to life', N'活過來', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('78', N'come up with something', N'想出，提出 (計畫、答案等 )', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('79', N'come upon . . .', N'偶然遇見 …，偶然發現 …', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('80', N'consist of . . .', N'由…組成、構成', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('81', N'cost someone dearly', N'使某人付出沉重代價', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('82', N'couldn’t  care less (infml .)', N'毫不在乎', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('83', N'cover up something', N'掩飾，掩蓋 (錯誤、罪行等 )', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('84', N'crowd into something', N'大量湧入某處，大批擠進某處', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('85', N'crowd out . . .', N'排擠 …', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('86', N'cut down  (on something)', N'減少 (…)', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('87', N'dawn on someone', N'使某人開始明白', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('88', N'day after day', N'每天，一天天', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('89', N'day in, day out', N'日復一日', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('90', N'deal with something', N'處理 …，解決 …', N'Unit 03');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('91', N'depend on . . .', N'依賴 …，依靠 …', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('92', N'deprive . . . of something', N'從…剝奪某物，使 …失去某物', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('93', N'derive something from something', N'從…中獲得 …', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('94', N'die off', N'相繼死去', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('95', N'dig in (infml. )', N'開動', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('96', N'dig into something', N'探究某事', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('97', N'disappear off the face of the earth', N'消失得無影無蹤', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('98', N'dish out something', N'分配某物', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('99', N'drive . . . out', N'驅離 …', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('100', N'drive off', N'(駕駛 )駕車離去， (車輛 )開走', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('101', N'drop out (of something)', N'退出 (學校或活動 )', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('102', N'due to . . .', N'因為 …，由於 …', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('103', N'end up (doing something)', N'最後處於 (…)，結果成為 (…)', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('104', N'engage in something', N'參加 …，從事 …', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('105', N'even though', N'即使，雖然', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('106', N'every penny', N'每一分錢，所有的錢', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('107', N'fade out', N'使(畫面 )淡出，使 (聲音 )漸弱', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('108', N'far from (doing) something', N'完全不 …，根本不 …', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('109', N'fight off something', N'擊退 …，克服 …', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('110', N'first and foremost', N'首先，首要的是', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('111', N'first of all', N'第一，首先', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('112', N'fit in', N'適應', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('113', N'flash back (to something)', N'回想起  (某事 )', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('114', N'food for thought', N'引人深思的事物', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('115', N'for instance  = for example', N'例如', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('116', N'for sure  (infml.)', N'肯定，一定', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('117', N'forgive and forget', N'完全原諒，不念舊惡', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('118', N'from time to time', N'偶爾，有時', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('119', N'get around', N'四處走動，旅行； (消息、訊息等 ) 傳開，流傳', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('120', N'get at  something', N'查明 …，瞭解 …', N'Unit 04');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('121', N'get away (from . . . )', N'(從…)離開， (從…)逃離', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('122', N'get behind (with something)', N'(在…方面 )落後', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('123', N'get into something', N'養成某種習慣', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('124', N'get out of something', N'逃避 …，擺脫 …', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('125', N'get over  . . .', N'從…中恢復常態', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('126', N'get rid of . . .', N'擺脫…，除掉 …；丟棄 …，扔掉 …', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('127', N'give someone  a break  (infml. )', N'饒了、放過某人', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('128', N'go a long way toward doing something', N'對做某事有幫助', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('129', N'go beyond something', N'超出 …，超過 …', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('130', N'go by', N'(時間 )流逝', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('131', N'go by something', N'遵循某事物，遵從某事物', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('132', N'go on', N'發生，進行', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('133', N'go on to do something', N'(完成某事後 ) 接著做另一件事', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('134', N'go to . . .', N'給予 …，由 …得到', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('135', N'go to extremes', N'採取極端的手段', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('136', N'grow out of something', N'產生於 …，源自於 …', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('137', N'had better', N'最好 …，還是 (做)…好', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('138', N'hang out (with someone)', N'(與…)閒晃、廝混', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('139', N'hang up', N'掛斷 (電話 )', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('140', N'have a way of doing something  …', N'是常有的事，有 …的習慣', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('141', N'have no idea', N'不知道，不瞭解', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('142', N'have no need of something', N'不需要某物', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('143', N'have nothing to do with . . .', N'與…無關', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('144', N'have one’s eye on someone', N'看上 …，看中 …', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('145', N'have second thoughts', N'(經過考慮後 )改變主意，改變想法', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('146', N'have something in common', N'(和某人的想法、興趣等方面 )有共同之； (和某物或某處的特點 )有相同、相似之處', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('147', N'hit home', N'使(某人 )深切感受到', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('148', N'hit it big  (infml. )', N'成功', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('149', N'hit the roof (infml. )', N'勃然大怒，生氣', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('150', N'hunt someone down', N'追捕某人，追緝某人', N'Unit 05');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('151', N'in accord (with . . . )', N'與…一致，融洽', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('152', N'in addition (to . . . )', N'除…之外 (還)', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('153', N'in advance (of something)', N'(在…)之前，事先', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('154', N'in comparison (with . . . )', N'(與…)相比較', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('155', N'in control', N'保持冷靜，處之泰然；掌控，操控 (機構或局勢 )', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('156', N'in fact', N'實際上，事實上', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('157', N'in honor of . . .', N'向…致敬', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('158', N'in no way', N'一點也不', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('159', N'in one’s presence', N'在某人面前', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('160', N'in other  words', N'換句話說', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('161', N'in place of . . .', N'代替 …，取代 …', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('162', N'in preference to . . .', N'而非 …，並非 …', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('163', N'in reality', N'事實上', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('164', N'in return (for something)', N'作為  (對某事的 ) 回報', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('165', N'in some ways', N'某種程度上', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('166', N'in someone’s  eyes', N'在某人看來，在某人心目中', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('167', N'in spite of something', N'儘管 …', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('168', N'in the course of time  = eventually', N'總有一天，最終', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('169', N'in the dead of night', N'夜深人靜時', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('170', N'in the hands of someone', N'受…控制', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('171', N'in the long  term', N'從長期來看', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('172', N'in the meantime', N'在此時，期間', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('173', N'in time', N'及時，來得及', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('174', N'keep . . . in mind', N'記住 …，考慮 …', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('175', N'keep ( . . . ) out (of something)', N'不使 (…)進入 (某地 )', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('176', N'keep (someone) out of something', N'使(某人 )不捲入 …，使 (某人 )不受 …影響', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('177', N'keep an open mind', N'不懷成見，願意聽取他人的意見', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('178', N'keep down something', N'抑制某物增長，使某物不增加', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('179', N'keep off something', N'避免吃某物', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('180', N'keep up with . . .', N'跟上 …，趕上 …', N'Unit 06');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('181', N'kill time', N'打發時間，消磨時光', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('182', N'knock on wood', N'敲木頭 (希望留住好運、避免厄運時說的話 )', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('183', N'know no bounds', N'無窮無盡', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('184', N'last but not least', N'最後但同樣重要地', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('185', N'lay down something', N'制定，明訂 (規定或法律等 )', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('186', N'leave something alone', N'別動、別碰某物', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('187', N'lend oneself to something', N'適合某事物，適用於某事物', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('188', N'let us say', N'比方說，例如', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('189', N'live on something', N'以某食維生', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('190', N'live up to something', N'達到 (期待 )，履行  (諾言 )', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('191', N'live with something', N'忍受某事物', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('192', N'look around (something)', N'參訪 (某地 )', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('193', N'look for . . .', N'尋找 …', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('194', N'look forward to (doing) something', N'高興地期待、盼望  (做) 某事', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('195', N'look into something', N'調查 …', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('196', N'look someone up and down', N'(批判性地 )打量某人', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('197', N'look up something', N'查閱 …，搜尋 …', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('198', N'lose one’s heart (to someone)', N'愛上 (某人 )', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('199', N'lose touch (with . . . )', N'(與…)失去聯繫', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('200', N'make  (the)  headlines :', N'成為重要新聞、頭條', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('201', N'make  for something', N'導致某事，促成某事', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('202', N'make friends (with someone)', N'(和…)交朋友', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('203', N'make fun of . . .', N'嘲笑 …，取笑 …', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('204', N'make it', N'及時趕到', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('205', N'make oneself understood', N'把自己的意思表達清楚', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('206', N'make peace (with someone)', N'(與某人 )談和', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('207', N'make sense', N'合乎情理，明智；說得通，易於理解', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('208', N'make up one’s mind', N'下定決心', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('209', N'make up something', N'編造 (藉口、謊言等 ); 組成 …，構成 …', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('210', N'make use of . . .', N'利用 …，使用 …', N'Unit 07');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('211', N'many a(n)', N'大量，許多', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('212', N'mistake . . . for . . .', N'把…誤認為 …', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('213', N'more often than not  = usually', N'多半，往往', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('214', N'move  on (to something)', N'接著進行 (不同的事 )', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('215', N'no longer', N'不再', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('216', N'no more than', N'僅僅', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('217', N'no wonder =  it is no wonder that', N'難怪', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('218', N'not to mention something', N'更不用說 …', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('219', N'nothing but', N'只有', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('220', N'now and then', N'偶爾', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('221', N'nowhere in sight', N'看不到，找不到', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('222', N'nowhere to be found', N'找不到', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('223', N'occur to someone', N'某人想到 …，想起 …', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('224', N'on account of . . .', N'因為 …', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('225', N'on behalf of someone', N'代表某人', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('226', N'on duty', N'值班，值勤', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('227', N'on occasion', N'偶爾，不時', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('228', N'on the off chance', N'碰運氣', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('229', N'on the other hand', N'另一方面', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('230', N'on the outside', N'表面上，由外表看來', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('231', N'on the right  track', N'依循正確的方式', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('232', N'on the spot', N'當下，立刻', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('233', N'on the way', N'(嬰兒 )尚未出生；即將到來，就要發生', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('234', N'on the whole', N'大體上來說，大致而言', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('235', N'once again', N'再一次', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('236', N'once in a while', N'偶爾，有時候', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('237', N'one’s heart is in one’s mouth', N'提心吊膽， 緊張害怕', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('238', N'only if', N'唯若 …才，只有當', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('239', N'open one’s eyes (to something)', N'使某人 (對…)開眼界、長見識', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('240', N'open one’s heart (to someone)', N'(向某人 ) 敞開心扉', N'Unit 08');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('241', N'open up', N'暢所欲言，開誠布公', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('242', N'or so', N'大約', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('243', N'over and over (again)', N'再三地，一再地', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('244', N'owing  to something', N'因為某事', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('245', N'pass away', N'去世，過世', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('246', N'pass on something (to someone)', N'傳遞某物 (給某人 )', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('247', N'pay off', N'成功，有所回報', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('248', N'pay someone back (s th.)', N'償還某人 (人情、恩惠 )；償還某人 (金錢 )', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('249', N'pick up something', N'撿起 …，拿起 …; (偶然 )得到 …，學會 …', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('250', N'play a part (in something)', N'參與 (…)，對 (…)有影響', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('251', N'pluck up the courage (to do something)', N'鼓起勇氣 (…)', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('252', N'point of view', N'觀點', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('253', N'pop the question  (infml.)', N'求婚', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('254', N'pour out one’s heart', N'傾訴，傾吐', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('255', N'press  for something', N'不停要求某事物，持續要求某事物', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('256', N'pull up (something)', N'(駕駛 )停車， (車輛 )停止', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('257', N'put (something) to (good) use', N'有效利用 (某物 )', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('258', N'put aside something', N'儲存某物，保留某物', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('259', N'put off (doing) something', N'拖延 …，延宕 …', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('260', N'put on something', N'塗抹某物；穿戴某物', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('261', N'put up with . . .', N'忍受 …，容忍 …', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('262', N'rather than', N'而不是', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('263', N'reach out to someone', N'向…伸出援手，對 …提供援助', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('264', N'read (something) into something', N'(對某事 ) 過度解釋、解讀', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('265', N'refer to . . . as something', N'將…稱作某物', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('266', N'rely on . . .', N'(為生活、生存 )依賴 …；信賴 …，信任 …', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('267', N'remember the new  words.  when it comes to (doing) something', N'說到、提及 (做)某事', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('268', N'result in something', N'導致 …，造成 …', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('269', N'revenge oneself on someone', N'向某人報復，對某人報仇', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('270', N'ring out', N'(聲音 ) 響亮，清晰可聞', N'Unit 09');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('271', N'roll down something', N'搖下 (車窗 )', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('272', N'round up . . .', N'圍捕 …；將 …聚集起來', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('273', N'run into something', N'遭遇 (困難、麻煩等 )', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('274', N'save (one’s) face', N'(給…)留面子', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('275', N'second to none', N'不亞於，首屈一指', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('276', N'see the light', N'終於明白、領悟', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('277', N'set out', N'出發，啟程； (懷著目標 )開始工作', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('278', N'set up something', N'設立 …，創立 …', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('279', N'settle a/the score (with sb. )', N'報復  (某人 )，(和某人 ) 算帳', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('280', N'settle down', N'定居下來', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('281', N'sit back', N'不採取行動，袖手旁觀', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('282', N'size up . . .', N'評估 …，判斷 …', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('283', N'sleep in', N'晚起，睡懶覺', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('284', N'something can’t/doesn’t compare (with something else)', N'不能  (與某事) 相比', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('285', N'sow the seeds of something', N'播下 …的種子，成為 …的肇端', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('286', N'spare one’s feelings', N'不使某人難過，顧及某人的感受', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('287', N'spice up something', N'為某物增添趣味', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('288', N'stay up', N'熬夜，不睡覺', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('289', N'steep oneself in something', N'沉浸於 …', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('290', N'stem from something', N'起源於某事物，由某事物引起', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('291', N'stick to something', N'維持 …，堅持 …', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('292', N'stir up something', N'挑起 …，煽動 …', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('293', N'stop by ( . . . )', N'順路拜訪  (…)', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('294', N'strike a balance (between . . . and . . . )', N'求得平衡，折衷', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('295', N'swarm with . . .', N'擠滿 …，到處是 …', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('296', N'sweep away something', N'徹底消除 …，消滅 …', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('297', N'take . . . for granted', N'將…視為理所當然', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('298', N'take a bow', N'謝幕，鞠躬答謝', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('299', N'take advantage of . . .', N'利用 …', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('300', N'take flight', N'逃走', N'Unit 10');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('301', N'take its toll (on . . . )', N'(對…)產生不良影響 、造成重大 損失', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('302', N'take on something', N'接受  (工作 )，承擔  (責任 )', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('303', N'take part in something', N'參加 …', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('304', N'take root', N'(思想 ) 深入人心； (植物 ) 生根', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('305', N'take someone’s  life', N'殺死某人，取某人性命', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('306', N'take the place of . . .', N'代替 …，頂替 …', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('307', N'tear apart something', N'拆散某物，使某物分崩離析', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('308', N'thanks to …', N'幸虧 …，由於 …', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('309', N'that is (to say)', N'意即，也就是說', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('310', N'the recesses of something', N'(某物的 ) 隱蔽處； (情感、思想的 ) 深處', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('311', N'the talk of something', N'(某地 )人人談論的話題', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('312', N'these days  (infml.)', N'現今，如今', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('313', N'think  of . . . as . . .', N'把…看作 …，將 …視為 …', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('314', N'think of . . .', N'為…著想、設想；想到 …，構思出 …', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('315', N'think twice (about doing sth.)', N'三思而行，仔細考慮 (…)', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('316', N'time after time', N'一再地，再三地', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('317', N'to . . . extent', N'到達 …的程度', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('318', N'to the fullest', N'充分地', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('319', N'together with . . .', N'連同 …，和 …一起', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('320', N'track down . . .', N'(經長時間 )追蹤到 …', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('321', N'true to life', N'逼真，寫實的', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('322', N'tuck someone in', N'替某人蓋被子', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('323', N'turn  down  . . .', N'拒絕 …，回絕 …', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('324', N'turn into . . .', N'變成…', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('325', N'turn off something', N'關掉 (電源、水等 )', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('326', N'turn out', N'發展為，結果是', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('327', N'turn to . . .', N'求助於 …', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('328', N'turn up', N'(出其不意地 )出現', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('329', N'two peas in a pod', N'一模一樣', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('330', N'up to something', N'(數量、程度等 )至多可達 …', N'Unit 11');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('331', N'wait for their winter vacation to  begin.  warm  up', N'變暖，暖和起來', N'Unit 12');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('332', N'warn someone off (something)', N'告誡某人不要 …', N'Unit 12');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('333', N'wear away (something)', N'磨損 (…)as well (as . . . )', N'Unit 12');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('334', N'what if . . .  = what would happen, if…', N'要是 …會怎麼樣', N'Unit 12');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('335', N'what is more', N'再者，而且', N'Unit 12');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('336', N'what’s the use (of doing something)', N'(做某事 )沒有意義、用處', N'Unit 12');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('337', N'win the heart of someone', N'贏得 …的心', N'Unit 12');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('338', N'wipe up (something)', N'擦拭 (…)，抹掉 (…)', N'Unit 12');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('339', N'with a view to (doing) something', N'為了 …，以 …為目的', N'Unit 12');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('340', N'with open arms', N'熱情地，熱烈地', N'Unit 12');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('341', N'without a doubt', N'毫無疑問地', N'Unit 12');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('342', N'work on something', N'致力於某事', N'Unit 12');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('343', N'work out', N'成功地發展', N'Unit 12');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('344', N'would do well to do something', N'建議 (做…)，應該 …比較好', N'Unit 12');
INSERT INTO phrase_all (Orders, Phrase, Chinese, Unit) VALUES ('345', N'would rather . . . (than . . . )', N'寧願 …，寧可 …', N'Unit 12');
