CREATE TABLE phrase_ast 
(
    Orders int,
    Year nvarchar(300),
    Phrase nvarchar(300) primary key,
    Chinese	nvarchar(300),
    Unit nvarchar(300)
);

INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('1', N'104', N'above all', N'最重要的 ; 尤其', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('2', N'106', N'accustomed to', N'習慣於', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('3', N'108', N'among others', N'其中 ; 尤其', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('4', N'102', N'as a result', N'由於', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('5', N'107', N'as a result of', N'由於', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('6', N'104', N'as it appears', N'看起來', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('7', N'102', N'as soon as', N'⼀ ... 就', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('8', N'100', N'as usual', N'照例 ; 照常', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('9', N'101', N'as well as', N'以及', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('10', N'105', N'aside from', N'besides 除此之外 ( 包含 );except for 除了 … 之外 ( 不包含 )', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('11', N'108', N'at best', N'充其量 ; 頂多', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('12', N'100', N'at fault', N'有責任 ; 有錯', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('13', N'108', N'at large', N'逍遙法外 ;普遍地 ; 全體地', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('14', N'101', N'back up', N'備份', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('15', N'101', N'battle for', N'為 …… 鬥爭', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('16', N'106', N'blessed with', N'在 ... ⽅⾯有福', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('17', N'110', N'break through', N'突破 ; 打破', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('18', N'102', N'by all means', N'好的 ; 當然', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('19', N'101', N'by and large', N'總體上，⼀般來說', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('20', N'108', N'by contrast', N'相比之下', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('21', N'101', N'call out', N'⼤聲地喊', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('22', N'109', N'carry on', N'繼續', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('23', N'109', N'catch up', N'趕上', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('24', N'104', N'cater to', N'滿⾜或提供需求', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('25', N'107', N'check out', N'檢查', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('26', N'105', N'close to', N'接近於 ; 靠近', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('27', N'104', N'come across', N'碰到', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('28', N'101', N'compete against', N'與 ... 競爭', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('29', N'109', N'correspond to', N'相當於 ; 符合', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('30', N'106', N'crack down on', N'打擊 ; 鎮壓', N'Unit 01');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('31', N'104', N'depend on', N'取決於', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('32', N'102', N'ever since', N'從 ... 以來', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('33', N'106', N'familiar with', N'熟悉', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('34', N'109', N'fight for', N'為 ... ⽽戰', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('35', N'101', N'fight over', N'爭奪 ; 為 ... 爭吵', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('36', N'107', N'for the sake of', N'由於 ; 為了', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('37', N'109', N'get off', N'離開', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('38', N'106', N'give in to', N'屈服 ; 讓步', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('39', N'104', N'go after sb/sth', N'追趕 ; 追捕 ;謀求 ; 追逐', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('40', N'101', N'head for', N'朝 ... 前進', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('41', N'110', N'heat up', N'加熱 ; 使 ... 變暖', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('42', N'104', N'identify with', N'認同 ( 某⼈ ); 與 ( 某⼈ ) 產⽣共鳴', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('43', N'108', N'if any', N'若有的話', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('44', N'105', N'in addition to', N'除 ... 之外', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('45', N'102', N'in case of', N'以防萬⼀', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('46', N'100', N'in place of', N'代替', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('47', N'108', N'in service', N'服勤中', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('48', N'110', N'in short', N'總⽽⾔之 ; 簡⽽⾔之', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('49', N'100', N'in some cases', N'在某些情況下', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('50', N'107', N'in spite of', N'儘管', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('51', N'100', N'in tears', N'哭泣', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('52', N'102', N'in the dark', N'蒙在⿎底 ; ⼀無所知', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('53', N'100', N'in the presence of', N'當著 ... 的⾯', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('54', N'101', N'in this regard', N'關於 ; 在這點上', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('55', N'105', N'long before', N'很早以前 ; 很久以前', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('56', N'106', N'look out for', N'照顧 ;留⼼ ; 注意尋找', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('57', N'100', N'off guard', N'毫無防備', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('58', N'102', N'off the record', N'下說的 ; 不供發表的', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('59', N'101', N'on behalf of', N'代表', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('60', N'100', N'on call', N'待命', N'Unit 02');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('61', N'101', N'on one''s own', N'獨⾃', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('62', N'102', N'on the other hand', N'另⼀⽅⾯', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('63', N'102', N'on the rise', N'在上升', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('64', N'100', N'on top of', N'除 ... 之外', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('65', N'101', N'one on one', N'⼀對⼀', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('66', N'101', N'opposed to', N'反對', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('67', N'102', N'out of luck', N'運氣不好', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('68', N'100', N'over and over', N'⼀遍⼜⼀遍', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('69', N'101', N'pass on', N'放棄', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('70', N'109', N'persist in', N'堅持', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('71', N'106', N'put up with', N'容忍 ; 忍受', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('72', N'109', N'serve as', N'充當 ; 起 … 的作⽤', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('73', N'101', N'so much as', N'甚⾄於', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('74', N'102', N'so that', N'為了 ; 以便', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('75', N'105', N'soon after', N'不久之後', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('76', N'107', N'speak of', N'談到 ; 論及', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('77', N'106', N'subject to', N'受到 … 的影響', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('78', N'104', N'sweep through', N'席捲', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('79', N'100', N'to be frank', N'老實說', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('80', N'104', N'to some extent', N'在某種程度上', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('81', N'107', N'to the best of... (my knowledge/my ability)', N'就我所知 / 就我能⼒所及', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('82', N'109', N'toss out', N'丟棄 ; 扔掉', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('83', N'107', N'trade with', N'和 … 貿易', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('84', N'108', N'under control', N'在掌控之下', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('85', N'102', N'warm up', N'暖⾝', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('86', N'107', N'watch over', N'保護 ; 照顧', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('87', N'110', N'wear out', N'磨損 ; 耗盡', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('88', N'105', N'with respect to', N'關於 ; ⾄於', N'Unit 03');
INSERT INTO phrase_ast (Orders, Year, Phrase, Chinese, Unit) VALUES ('89', N'100', N'with the help of', N'在 ... 的幫助下', N'Unit 03');
